#!/usr/bin/env python3
"""Generate the Java Block Kit model from java/generator/model.json.

model.json is the language-neutral description of every generated value type: its Slack
wire type, the Java type of every field, required fields, validation rules, descriptions,
and Slack documentation links. spec/limits.json supplies the documented limits.

Usage:
    python3 java/generator/generate_models.py            # write Java sources
    python3 java/generator/generate_models.py --check-go # also compare with the Go registry
    cd java && ./mvnw spotless:apply                    # format the output (JDK 21+)

--check-go fails when the Java model and go/internal/builder_methods.json disagree about
which fields a builder exposes, so the two implementations cannot drift silently.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
JAVA = ROOT / "java"
MODEL = JAVA / "generator/model.json"
LIMITS = ROOT / "spec/limits.json"
OUTPUT = JAVA / "src/main/java/io/github/nicklambourne/slackblocks"
BASE_PACKAGE = "io.github.nicklambourne.slackblocks"
MARKER = "// Generated by java/generator/generate_models.py from java/generator/model.json."
PACKAGES = ("block", "element", "object", "payload")
TEXT_OBJECT_TYPES = {"PlainText", "MarkdownText"}


def camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def sentence(text: str) -> str:
    text = text.strip()
    return text if text.endswith(".") else text + "."


class Model:
    def __init__(self, data: dict, limits: dict) -> None:
        self.data = data
        self.limits = limits
        self.packages: dict[str, str] = {"RichTextStyle": "object"}
        for item in data["interfaces"] + data["enums"] + data["types"]:
            self.packages[item["name"]] = item["package"]

    def qualified(self, name: str) -> str:
        return f"{BASE_PACKAGE}.{self.packages[name]}.{name}"

    def limit_sentence(self, path: str) -> str:
        node: object = self.limits
        for part in path.split("."):
            node = node[part]  # type: ignore[index]
        assert isinstance(node, dict), path
        if "item_max_length" in node:
            return (
                f"Slack allows at most {node['max_items']} items, each at most "
                f"{node['item_max_length']} characters."
            )
        if "min_length" in node or "max_length" in node:
            low, high = node.get("min_length"), node.get("max_length")
            if low and high:
                return f"Must be between {low} and {high} characters."
            if high:
                return f"Slack allows at most {high} characters."
            return "Must not be empty."
        if "min_items" in node or "max_items" in node:
            low, high = node.get("min_items"), node.get("max_items")
            if low and high:
                return f"Must contain between {low} and {high} items."
            if high:
                return f"Slack allows at most {high} items."
            return f"Must contain at least {low} items."
        if "min" in node or "max" in node:
            low, high = node.get("min"), node.get("max")
            if low is not None and high is not None:
                return f"Must be between {low} and {high}."
            return f"Must be at most {high}." if high is not None else f"Must be at least {low}."
        if "exclusive_min" in node:
            return f"Must be greater than {node['exclusive_min']}."
        raise ValueError(f"Unsupported limit at {path}: {node}")


class Imports:
    def __init__(self, package: str) -> None:
        self.package = package
        self.names: set[str] = set()

    def add(self, qualified: str) -> None:
        if qualified.rsplit(".", 1)[0] not in (self.package, "java.lang"):
            self.names.add(qualified)

    def render(self) -> str:
        return "\n".join(f"import {name};" for name in sorted(self.names))


def javadoc(lines: list[str], indent: str) -> str:
    body = [f"{indent} *" + (f" {line}" if line else "") for line in lines]
    return "\n".join([f"{indent}/**", *body, f"{indent} */"])


def field_doc(model: Model, field: dict, extra: list[str], params: list[tuple[str, str]]) -> list[str]:
    lines = [sentence(field["description"])]
    notes = []
    if field.get("required"):
        notes.append("Required.")
    if field.get("limits"):
        notes.append(model.limit_sentence(field["limits"]))
    notes.extend(extra)
    if notes:
        lines += ["", "<p>" + " ".join(notes)]
    lines.append("")
    lines += [f"@param {name} {description}" for name, description in params]
    lines.append("@return this builder")
    return lines


def method(doc: list[str], signature: str, body: list[str], annotations: tuple[str, ...] = ()) -> str:
    parts = [javadoc(doc, "    ")]
    parts += [f"    {annotation}" for annotation in annotations]
    parts.append(f"    public {signature} {{")
    parts += [f"      {line}" for line in body]
    parts += ["      return this;", "    }"]
    return "\n".join(parts)


def field_methods(model: Model, owner: dict, field: dict, imports: Imports) -> list[str]:
    name, wire, kind = field["method"], field["wire"], field["kind"]
    target = field.get("type")
    if target:
        imports.add(model.qualified(target))
    code = f"{{@code {wire}}}"
    scalar = {"string": "String", "boolean": "boolean", "int": "int", "long": "long", "double": "double"}
    if kind in scalar:
        return [method(
            field_doc(model, field, [], [("value", f"value for Slack's {code} field")]),
            f"Builder {name}({scalar[kind]} value)",
            [f'state.set("{wire}", value);'],
        )]
    if kind == "stringList":
        return [method(
            field_doc(model, field, ["Each call appends to any values already added."], [("values", "values appended in order")]),
            f"Builder {name}(String... values)",
            [f'state.append("{wire}", (Object[]) values);'],
        )]
    if kind == "enum":
        return [method(
            field_doc(model, field, [], [("value", f"value for Slack's {code} field")]),
            f"Builder {name}({target} value)",
            [f'state.set("{wire}", Objects.requireNonNull(value, "{name}").wireValue());'],
        )]
    if kind == "number":
        return [
            method(
                field_doc(model, field, ["Whole numbers are sent without a decimal point."], [("value", "whole-number value")]),
                f"Builder {name}(long value)",
                [f'state.set("{wire}", value);'],
            ),
            method(
                field_doc(model, field, ["Prefer {@link #value(long)} for whole numbers."], [("value", "decimal value")]),
                f"Builder {name}(double value)",
                [f'state.set("{wire}", value);'],
            ),
        ]
    if kind == "map":
        imports.add(f"{BASE_PACKAGE}.internal.WireObjects")
        return [method(
            field_doc(model, field, [], [("value", "map of strings, numbers, booleans, lists, and maps")]),
            f"Builder {name}(Map<String, ?> value)",
            [f'state.set("{wire}", WireObjects.requireWireValue("{name}", value));'],
        )]
    if kind == "object":
        return [method(
            field_doc(model, field, [], [("value", f"nested {{@link {target}}}")]),
            f"Builder {name}({target} value)",
            [f'state.set("{wire}", value);'],
        )]
    if kind == "list":
        return [method(
            field_doc(model, field, ["Each call appends to any values already added."], [("values", f"{{@link {target}}} values appended in order")]),
            f"Builder {name}({target}... values)",
            [f'state.append("{wire}", (Object[]) values);'],
        )]
    if kind == "rows":
        imports.add("java.util.List")
        return [method(
            field_doc(model, field, ["Each call appends to any rows already added."], [("rows", f"rows of {{@link {target}}} values, in display order")]),
            f"final Builder {name}(List<? extends {target}>... rows)",
            [f'state.append("{wire}", (Object[]) rows);'],
            ("@SafeVarargs", "@SuppressWarnings(\"varargs\") // rows are copied into an Object list, never exposed"),
        )]
    if kind == "text":
        coerce = field["coerce"]
        imports.add(f"{BASE_PACKAGE}.internal.WireObjects")
        methods = [
            method(
                field_doc(model, field, [f"The string is sent as a {{@code {coerce}}} text object."], [("value", "text content")]),
                f"Builder {name}(String value)",
                [f'state.set("{wire}", WireObjects.text("{coerce}", Objects.requireNonNull(value, "{name}")));'],
            ),
            method(
                field_doc(model, field, [], [("value", f"a {{@link {target}}} object")]),
                f"Builder {name}({target} value)",
                [f'state.set("{wire}", value);'],
            ),
        ]
        if name == "text":
            alias = "plainText" if coerce == "plain_text" else "markdownText"
            methods.append(method(
                field_doc(model, field, [f"Equivalent to {{@link #text(String)}}."], [("value", "text content")]),
                f"Builder {alias}(String value)",
                ["text(value);"],
            ))
        return methods
    if kind == "textList":
        imports.add(f"{BASE_PACKAGE}.internal.WireObjects")
        coerce = field["coerce"]
        return [
            method(
                field_doc(model, field, ["Each call appends to any values already added."], [("values", f"{{@link {target}}} objects appended in order")]),
                f"Builder {name}({target}... values)",
                [f'state.append("{wire}", (Object[]) values);'],
            ),
            method(
                field_doc(model, field, [f"Each string is sent as a {{@code {coerce}}} text object."], [("values", "strings appended in order")]),
                f"Builder markdown{name[:1].upper()}{name[1:]}(String... values)",
                [
                    f'Objects.requireNonNull(values, "{name}");',
                    "for (String value : values) {",
                    f'  state.append("{wire}", WireObjects.text("{coerce}", Objects.requireNonNull(value, "{name}")));',
                    "}",
                ],
            ),
        ]
    if kind == "style":
        imports.add(model.qualified("RichTextStyle"))
        methods = [method(
            field_doc(model, field, ["Replaces any style flags already set."], [("value", "the complete text style")]),
            f"Builder {name}(RichTextStyle value)",
            [f'state.set("{wire}", value);'],
        )]
        for flag in field["flags"]:
            methods.append(method(
                [f"Sets whether the {{@code {flag}}} style is applied.", "", "@param value whether to apply the style", "@return this builder"],
                f"Builder {camel(flag)}(boolean value)",
                [f'state.merge("{wire}", "{flag}", value);'],
            ))
        return methods
    raise ValueError(f"Unsupported field kind {kind} on {owner['name']}.{wire}")


CONVENIENCE = {
    "PlainText": ("of", "String text", "builder().text(text).build()", "Creates and validates plain text in one call.", [("text", "text content")]),
    "MarkdownText": ("of", "String text", "builder().text(text).build()", "Creates and validates mrkdwn text in one call.", [("text", "mrkdwn content")]),
    "RawText": ("of", "String text", "builder().text(text).build()", "Creates and validates a raw text cell in one call.", [("text", "cell text")]),
    "DividerBlock": ("create", "", "builder().build()", "Creates a divider block with no block identifier.", []),
}
BUILDER_SHORTCUTS = {
    "HeaderBlock": ("String text", "builder().text(text)", "Starts a header builder with its required text.", [("text", "header text")]),
    "ButtonElement": ("String text, String actionId", "builder().text(text).actionId(actionId)", "Starts a button builder with its required label and action identifier.", [("text", "button label"), ("actionId", "identifier returned in interaction payloads")]),
    "Option": ("String text, String value", "builder().text(text).value(value)", "Starts an option builder with its required label and value.", [("text", "visible option label"), ("value", "application-defined value")]),
    "ImageBlock": ("String imageUrl, String altText", "builder().imageUrl(imageUrl).altText(altText)", "Starts an image builder with its required URL and alternative text.", [("imageUrl", "public image URL"), ("altText", "accessible image description")]),
}
BUILD_TRANSFORMS = {
    # Plan tasks are task cards without their "type" discriminator on the wire.
    "PlanBlock": ['if (state.get("tasks") instanceof List<?> tasks) {', '  state.set("tasks", WireObjects.withoutType(tasks));', "}"],
    # Accept six-digit colors without the leading hash, as the other implementations do.
    "Attachment": [
        'if (state.get("color") instanceof String color',
        "    && color.length() == 6",
        '    && !color.equals("danger")',
        '    && !color.equals("good")',
        '    && !color.equals("warning")) {',
        '  state.set("color", "#" + color);',
        "}",
    ],
}


def class_source(model: Model, spec: dict) -> str:
    name, package = spec["name"], spec["package"]
    imports = Imports(f"{BASE_PACKAGE}.{package}")
    for qualified in (
        "com.google.gson.annotations.JsonAdapter",
        f"{BASE_PACKAGE}.Buildable",
        f"{BASE_PACKAGE}.ValidationException",
        f"{BASE_PACKAGE}.internal.BuilderState",
        f"{BASE_PACKAGE}.internal.SlackObjectJsonAdapter",
        "java.util.Map",
        "java.util.Objects",
    ):
        imports.add(qualified)
    interfaces = list(spec["implements"])
    if package == "block":
        interfaces.insert(0, "Block")
    elif package == "element" and "InputElement" not in interfaces:
        interfaces.insert(0, "Element")
    for interface in interfaces:
        imports.add(model.qualified(interface))
    if not interfaces:
        imports.add(f"{BASE_PACKAGE}.SlackObject")
        interfaces = ["SlackObject"]
    extends = ""
    if name in TEXT_OBJECT_TYPES:
        imports.add("com.slack.api.model.block.composition.TextObject")
        extends = " extends TextObject"
    elif package == "element":
        imports.add("com.slack.api.model.block.element.BlockElement")
        extends = " extends BlockElement"
    if name in BUILD_TRANSFORMS:
        imports.add(f"{BASE_PACKAGE}.internal.WireObjects")
    if name == "PlanBlock":
        imports.add("java.util.List")

    methods = []
    for field in spec["fields"]:
        methods.extend(field_methods(model, spec, field, imports))

    class_doc = [sentence(spec["description"]), ""]
    class_doc.append(
        "<p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link"
        " Builder#build()} to validate and create an immutable value."
    )
    required = [f"{{@code {field['method']}}}" for field in spec["fields"] if field.get("required")]
    rules = [f"Required: {', '.join(required)}."] if required else []
    rules += spec.get("rules", [])
    if rules:
        class_doc += ["", "<ul>", *[f"  <li>{rule}" for rule in rules], "</ul>"]
    class_doc += ["", f'@see <a href="{spec["docUrl"]}">Slack reference</a>']

    statics = []
    if name in BUILDER_SHORTCUTS:
        parameters, expression, description, params = BUILDER_SHORTCUTS[name]
        statics.append("\n".join([
            javadoc([description, "", *[f"@param {p} {d}" for p, d in params], "@return a new builder"], "  "),
            f"  public static Builder builder({parameters}) {{",
            f"    return {expression};",
            "  }",
            "",
        ]))
    if name in CONVENIENCE:
        factory, parameters, expression, description, params = CONVENIENCE[name]
        statics.append("\n".join([
            javadoc([description, "", *[f"@param {p} {d}" for p, d in params], f"@return an immutable {name}",
                     "@throws ValidationException if the value breaks a Block Kit rule"], "  "),
            f"  public static {name} {factory}({parameters}) {{",
            f"    return {expression};",
            "  }",
            "",
        ]))

    text_accessors = ""
    if name in TEXT_OBJECT_TYPES:
        text_accessors = """
  /**
   * Returns the Slack text representation type.
   *
   * @return Slack wire type
   */
  @Override
  public String getType() {
    return (String) Objects.requireNonNull(values.get("type"));
  }

  /**
   * Returns the text content.
   *
   * @return text content
   */
  @Override
  public String getText() {
    return (String) Objects.requireNonNull(values.get("text"));
  }
"""

    defaults = []
    for field, value in spec["defaults"].items():
        literal = str(value).lower() if isinstance(value, bool) else json.dumps(value) if isinstance(value, str) else str(value)
        defaults.append(f'      state.set("{field}", {literal});')
    transform = "".join(f"      {line}\n" for line in BUILD_TRANSFORMS.get(name, []))
    statics_source = "\n".join(statics)
    method_source = "\n\n".join(methods)

    return f"""{MARKER}
package {BASE_PACKAGE}.{package};

{imports.render()}

{javadoc(class_doc, "")}
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class {name}{extends} implements {", ".join(interfaces)} {{
  private final Map<String, Object> values;
  private final int hash;

  private {name}(Map<String, Object> values) {{
    this.values = values;
    this.hash = values.hashCode();
  }}

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {{
    return new Builder();
  }}

{statics_source}
  @Override
  public Map<String, Object> toMap() {{
    return values;
  }}
{text_accessors}
  @Override
  public boolean equals(Object other) {{
    return this == other || (other instanceof {name} that && values.equals(that.values));
  }}

  @Override
  public int hashCode() {{
    return hash;
  }}

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {{
    return toJson();
  }}

  /** Fluent builder for {{@link {name}}}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<{name}> {{
    private final BuilderState state = new BuilderState("{name}", "{spec['wireType']}");

    private Builder() {{
{chr(10).join(defaults)}
    }}

{method_source}

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method.
     * Prefer the named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {{
      if (field.isEmpty()) {{
        throw new IllegalArgumentException("field must not be empty");
      }}
      state.set(field, value);
      return this;
    }}

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {{@link {name}}}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public {name} build() {{
{transform}      return state.build({name}::new);
    }}
  }}
}}
"""


def implementers(model: Model, interface: str) -> list[str]:
    result = []
    for item in model.data["types"]:
        if (
            interface in item["implements"]
            or (interface == "Block" and item["package"] == "block")
            or (interface == "Element" and item["package"] == "element")
        ):
            result.append(item["name"])
    return sorted(result)


def interface_source(model: Model, spec: dict) -> str:
    name, package = spec["name"], spec["package"]
    imports = Imports(f"{BASE_PACKAGE}.{package}")
    names = implementers(model, name)
    for implementer in names:
        imports.add(model.qualified(implementer))
    doc = [sentence(spec["description"]), "", "<p>Implemented by " + ", ".join(f"{{@link {n}}}" for n in names) + "."]
    if name == "Block":
        imports.add(f"{BASE_PACKAGE}.SlackObject")
        imports.add("com.slack.api.model.block.LayoutBlock")
        imports.add("java.util.Objects")
        imports.add("org.jspecify.annotations.Nullable")
        body = """
  /**
   * Returns the Slack block type. Values are materialized once at build time, so this is a map
   * lookup rather than a rebuild.
   *
   * @return Slack wire type
   */
  @Override
  default String getType() {
    return (String) Objects.requireNonNull(toMap().get("type"));
  }

  /**
   * Returns the configured block identifier.
   *
   * @return block identifier, or {@code null} when none was set
   */
  @Override
  default @Nullable String getBlockId() {
    return (String) toMap().get("block_id");
  }
"""
        declaration = "public interface Block extends LayoutBlock, SlackObject {" + body + "}"
    else:
        parent = "Element" if name == "InputElement" else "SlackObject"
        if parent == "SlackObject":
            imports.add(f"{BASE_PACKAGE}.SlackObject")
        declaration = f"public interface {name} extends {parent} {{}}"
    return f"""{MARKER}
package {BASE_PACKAGE}.{package};

{imports.render()}

{javadoc(doc, "")}
{declaration}
"""


def enum_source(spec: dict) -> str:
    constants = []
    for index, constant in enumerate(spec["constants"]):
        terminator = ";" if index == len(spec["constants"]) - 1 else ","
        constants.append(f'  /** {sentence(constant["description"])} */\n  {constant["name"]}("{constant["wire"]}"){terminator}')
    joined = "\n\n".join(constants)
    return f"""{MARKER}
package {BASE_PACKAGE}.{spec["package"]};

/** {sentence(spec["description"])} */
public enum {spec["name"]} {{
{joined}

  private final String wireValue;

  {spec["name"]}(String wireValue) {{
    this.wireValue = wireValue;
  }}

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {{
    return wireValue;
  }}
}}
"""


def check_go(model: Model) -> list[str]:
    registry = json.loads((ROOT / "go/internal/builder_methods.json").read_text())
    problems = []
    seen = set()
    for spec in model.data["types"]:
        constructor = spec["goConstructor"]
        seen.add(constructor)
        go_methods = registry.get(constructor)
        if go_methods is None:
            problems.append(f"{spec['name']}: Go registry has no {constructor}")
            continue
        java_methods = [field["goMethod"] for field in spec["fields"] if field["goMethod"]]
        if sorted(java_methods) != sorted(go_methods):
            missing = sorted(set(go_methods) - set(java_methods))
            extra = sorted(set(java_methods) - set(go_methods))
            problems.append(f"{spec['name']}: missing Go methods {missing}, unknown Go methods {extra}")
    for constructor in sorted(set(registry) - seen - {"NewAccordionSection"}):
        problems.append(f"Go constructor {constructor} has no Java type in model.json")
    return problems


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check-go", action="store_true", help="compare model.json with the Go builder registry")
    arguments = parser.parse_args()

    model = Model(json.loads(MODEL.read_text()), json.loads(LIMITS.read_text()))
    if arguments.check_go:
        problems = check_go(model)
        if problems:
            print("Java model and Go builder registry disagree:", *problems, sep="\n  ", file=sys.stderr)
            sys.exit(1)

    written: set[Path] = set()

    def write(package: str, name: str, source: str) -> None:
        path = OUTPUT / package / f"{name}.java"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source)
        written.add(path)

    for spec in model.data["interfaces"]:
        write(spec["package"], spec["name"], interface_source(model, spec))
    for spec in model.data["enums"]:
        write(spec["package"], spec["name"], enum_source(spec))
    for spec in model.data["types"]:
        write(spec["package"], spec["name"], class_source(model, spec))
    for package in PACKAGES:
        for path in (OUTPUT / package).glob("*.java"):
            if path not in written and path.read_text().startswith(MARKER):
                path.unlink()
    print(
        f"Generated {len(model.data['types'])} value types, {len(model.data['interfaces'])} interfaces, "
        f"and {len(model.data['enums'])} enums."
    )


if __name__ == "__main__":
    main()
