"""Generator failures are tested in an isolated tree, never by editing the checkout."""

import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
import os
import tempfile
import unittest

SCRATCH = None
if Path("/Volumes/Repos").exists():
    for volume in ("Repos", "Cache", "Scratch"):
        if not os.path.ismount("/Volumes/" + volume):
            raise SystemExit("Required external volume is missing: " + volume)
    SCRATCH = "/Volumes/Scratch"

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("generator", HERE / "generate.py")
generator = importlib.util.module_from_spec(spec)
spec.loader.exec_module(generator)


class GeneratorTest(unittest.TestCase):
    def test_unknown_field_kind_fails(self):
        model = json.loads((generator.ROOT / "spec/model.json").read_text())
        model["types"][0]["fields"][0]["kind"] = "unsupported"
        with self.assertRaisesRegex(ValueError, "unknown field kind"):
            generator.generate(model, {}, {}, "1.2.0")

    def test_output_set_and_drift_are_detected(self):
        with tempfile.TemporaryDirectory(
            dir=SCRATCH, prefix="slackblocks-php-generator-"
        ) as directory:
            root = Path(directory)
            (root / "php/generator").mkdir(parents=True)
            shutil.copy(HERE / "generate.py", root / "php/generator/generate.py")
            shutil.copytree(generator.ROOT / "spec", root / "spec")
            cmd = [sys.executable, str(root / "php/generator/generate.py")]
            subprocess.run(cmd, check=True, capture_output=True)
            subprocess.run(cmd + ["--check"], check=True, capture_output=True)
            file = root / "php/src/PlainText.php"
            original = file.read_text()
            for mutation in ["missing", "stale", "extra"]:
                if mutation == "missing":
                    file.unlink()
                elif mutation == "stale":
                    file.write_text(original + "// stale\n")
                else:
                    (root / "php/src/Extra.php").write_text(
                        "// Generated by php/generator/generate.py.\n"
                    )
                result = subprocess.run(
                    cmd + ["--check"], capture_output=True, text=True
                )
                self.assertNotEqual(0, result.returncode, mutation)
                subprocess.run(cmd, check=True, capture_output=True)
            self.assertFalse((root / "php/src/Extra.php").exists())


if __name__ == "__main__":
    unittest.main()
