// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.block;

import java.util.Optional;

/** Severity levels supported by alert blocks. */
public enum AlertLevel {
  /** Neutral styling. */
  DEFAULT("default"),

  /** Informational styling. */
  INFO("info"),

  /** Warning styling. */
  WARNING("warning"),

  /** Error styling. */
  ERROR("error"),

  /** Success styling. */
  SUCCESS("success");

  private final String wireValue;

  AlertLevel(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }

  /**
   * Finds the constant for a Slack JSON value.
   *
   * @param wireValue the value Slack uses in JSON
   * @return the matching constant, or an empty optional for an unknown value
   */
  public static Optional<AlertLevel> fromWireValue(String wireValue) {
    for (AlertLevel constant : values()) {
      if (constant.wireValue.equals(wireValue)) {
        return Optional.of(constant);
      }
    }
    return Optional.empty();
  }
}
