// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Text;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * A severity-labelled alert, available in modals.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/alert-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class AlertBlock implements Block {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private AlertBlock(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the alert message.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Text getText() {
    return TypedFields.requiredText(fields, "AlertBlock", "text", Text.class);
  }

  /**
   * Returns the alert severity, which controls its color and icon.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<AlertLevel> getLevel() {
    return TypedFields.optionalEnum(fields, "AlertBlock", "level", AlertLevel::fromWireValue);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof AlertBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link AlertBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<AlertBlock> {
    private final BuilderState state = new BuilderState("AlertBlock", "alert");

    private Builder() {}

    /**
     * Sets the alert message.
     *
     * <p>Required. Slack allows at most 200 characters. The string is sent as a {@code mrkdwn} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the alert message.
     *
     * <p>Required. Slack allows at most 200 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder text(Text value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the alert message.
     *
     * <p>Required. Slack allows at most 200 characters. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder markdownText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets the alert severity, which controls its color and icon.
     *
     * @param value value for Slack's {@code level} field
     * @return this builder
     */
    public Builder level(AlertLevel value) {
      state.set("level", Objects.requireNonNull(value, "level").wireValue());
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link AlertBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public AlertBlock build() {
      return state.build(AlertBlock::new);
    }
  }
}
