// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.element.ButtonElement;
import io.github.nicklambourne.slackblocks.element.ImageElement;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.SlackIcon;
import io.github.nicklambourne.slackblocks.object.Text;
import java.util.Map;
import java.util.Objects;

/**
 * A compact card with an image, text, and up to three buttons.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Provide at least one of a hero image, title, actions, or body.
 *   <li>An image icon and a Slack icon cannot be combined.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/card-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class CardBlock implements Block {
  private final Map<String, Object> values;
  private final int hash;

  private CardBlock(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof CardBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link CardBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<CardBlock> {
    private final BuilderState state = new BuilderState("CardBlock", "card");

    private Builder() {}

    /**
     * Sets the image displayed prominently at the top of the card.
     *
     * @param value nested {@link ImageElement}
     * @return this builder
     */
    public Builder heroImage(ImageElement value) {
      state.set("hero_image", value);
      return this;
    }

    /**
     * Sets the image displayed beside the title.
     *
     * @param value nested {@link ImageElement}
     * @return this builder
     */
    public Builder icon(ImageElement value) {
      state.set("icon", value);
      return this;
    }

    /**
     * Sets the card title.
     *
     * <p>Slack allows at most 150 characters. The string is sent as a {@code mrkdwn} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder title(String value) {
      state.set("title", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "title")));
      return this;
    }

    /**
     * Sets the card title.
     *
     * <p>Slack allows at most 150 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder title(Text value) {
      state.set("title", value);
      return this;
    }

    /**
     * Sets the supporting text shown below the title.
     *
     * <p>Slack allows at most 150 characters. The string is sent as a {@code mrkdwn} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder subtitle(String value) {
      state.set("subtitle", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "subtitle")));
      return this;
    }

    /**
     * Sets the supporting text shown below the title.
     *
     * <p>Slack allows at most 150 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder subtitle(Text value) {
      state.set("subtitle", value);
      return this;
    }

    /**
     * Sets the main body text of the card.
     *
     * <p>Slack allows at most 200 characters. The string is sent as a {@code mrkdwn} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder body(String value) {
      state.set("body", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "body")));
      return this;
    }

    /**
     * Sets the main body text of the card.
     *
     * <p>Slack allows at most 200 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder body(Text value) {
      state.set("body", value);
      return this;
    }

    /**
     * Adds buttons displayed at the bottom of the card, in display order.
     *
     * <p>Slack allows at most 3 items. Each call appends to any values already added.
     *
     * @param values {@link ButtonElement} values appended in order
     * @return this builder
     */
    public Builder actions(ButtonElement... values) {
      state.append("actions", (Object[]) values);
      return this;
    }

    /**
     * Sets a Slack-provided icon displayed beside the title. Cannot be combined with an image icon.
     *
     * @param value nested {@link SlackIcon}
     * @return this builder
     */
    public Builder slackIcon(SlackIcon value) {
      state.set("slack_icon", value);
      return this;
    }

    /**
     * Sets the small print shown at the bottom of the card.
     *
     * <p>Slack allows at most 200 characters. The string is sent as a {@code mrkdwn} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder subtext(String value) {
      state.set("subtext", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "subtext")));
      return this;
    }

    /**
     * Sets the small print shown at the bottom of the card.
     *
     * <p>Slack allows at most 200 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder subtext(Text value) {
      state.set("subtext", value);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link CardBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public CardBlock build() {
      return state.build(CardBlock::new);
    }
  }
}
