// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.element.FeedbackButtonsElement;
import io.github.nicklambourne.slackblocks.element.IconButtonElement;

/**
 * A value that can appear in a context actions block: feedback buttons or an icon button.
 *
 * <p>Implemented by {@link FeedbackButtonsElement}, {@link IconButtonElement}.
 */
public interface ContextActionsElement extends SlackObject {}
