// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.object.Chart;
import java.util.Map;

/**
 * A titled pie, bar, area, or line chart.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code title}, {@code chart}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/data-visualization-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class DataVisualizationBlock implements Block {
  private final Map<String, Object> values;
  private final int hash;

  private DataVisualizationBlock(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof DataVisualizationBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /**
   * Fluent builder for {@link DataVisualizationBlock}. Builders are mutable and not thread-safe.
   */
  public static final class Builder implements Buildable<DataVisualizationBlock> {
    private final BuilderState state =
        new BuilderState("DataVisualizationBlock", "data_visualization");

    private Builder() {}

    /**
     * Sets the chart title.
     *
     * <p>Required. Slack allows at most 50 characters.
     *
     * @param value value for Slack's {@code title} field
     * @return this builder
     */
    public Builder title(String value) {
      state.set("title", value);
      return this;
    }

    /**
     * Sets the chart to display.
     *
     * <p>Required.
     *
     * @param value nested {@link Chart}
     * @return this builder
     */
    public Builder chart(Chart value) {
      state.set("chart", value);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link DataVisualizationBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public DataVisualizationBlock build() {
      return state.build(DataVisualizationBlock::new);
    }
  }
}
