// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.object.RawNumber;
import io.github.nicklambourne.slackblocks.object.RawText;

/**
 * A value that can appear as a data table cell: raw text, a raw number, or a rich text block.
 *
 * <p>Implemented by {@link RawNumber}, {@link RawText}, {@link RichTextBlock}.
 */
public interface DataTableCell extends SlackObject {}
