// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;

/**
 * Large, bold plain text that introduces a group of blocks.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/header-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class HeaderBlock implements Block {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private HeaderBlock(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Starts a header builder with its required text.
   *
   * @param text header text
   * @return a new builder
   */
  public static Builder builder(String text) {
    return builder().text(text);
  }

  /**
   * Returns the header text, shown in a larger bold font.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public PlainText getText() {
    return TypedFields.requiredText(fields, "HeaderBlock", "text", PlainText.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof HeaderBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link HeaderBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<HeaderBlock> {
    private final BuilderState state = new BuilderState("HeaderBlock", "header");

    private Builder() {}

    /**
     * Sets the header text, shown in a larger bold font.
     *
     * <p>Required. Slack allows at most 150 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("plain_text", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the header text, shown in a larger bold font.
     *
     * <p>Required. Slack allows at most 150 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder text(PlainText value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the header text, shown in a larger bold font.
     *
     * <p>Required. Slack allows at most 150 characters. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder plainText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link HeaderBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public HeaderBlock build() {
      return state.build(HeaderBlock::new);
    }
  }
}
