// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;

/**
 * A standalone image with alternative text and an optional title.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code imageUrl}, {@code altText}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/image-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class ImageBlock implements Block {
  private final Map<String, Object> values;
  private final int hash;

  private ImageBlock(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Starts an image builder with its required URL and alternative text.
   *
   * @param imageUrl public image URL
   * @param altText accessible image description
   * @return a new builder
   */
  public static Builder builder(String imageUrl, String altText) {
    return builder().imageUrl(imageUrl).altText(altText);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof ImageBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link ImageBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<ImageBlock> {
    private final BuilderState state = new BuilderState("ImageBlock", "image");

    private Builder() {}

    /**
     * Sets the publicly accessible URL of the image. Cannot be combined with a Slack file.
     *
     * <p>Required. Slack allows at most 3000 characters.
     *
     * @param value value for Slack's {@code image_url} field
     * @return this builder
     */
    public Builder imageUrl(String value) {
      state.set("image_url", value);
      return this;
    }

    /**
     * Sets a plain-text summary of the image or video for assistive technology.
     *
     * <p>Required. Slack allows at most 2000 characters.
     *
     * @param value value for Slack's {@code alt_text} field
     * @return this builder
     */
    public Builder altText(String value) {
      state.set("alt_text", value);
      return this;
    }

    /**
     * Sets the title shown above the image.
     *
     * <p>The string is sent as a {@code plain_text} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder title(String value) {
      state.set("title", WireObjects.text("plain_text", Objects.requireNonNull(value, "title")));
      return this;
    }

    /**
     * Sets the title shown above the image.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder title(PlainText value) {
      state.set("title", value);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link ImageBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public ImageBlock build() {
      return state.build(ImageBlock::new);
    }
  }
}
