// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.element.InputElement;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * A labelled input that collects a value in a modal, App Home, or message.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code label}, {@code element}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/input-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class InputBlock implements Block {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private InputBlock(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the label shown above the input.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public PlainText getLabel() {
    return TypedFields.requiredText(fields, "InputBlock", "label", PlainText.class);
  }

  /**
   * Returns the input element that collects the user's value.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public InputElement getElement() {
    return TypedFields.required(fields, "InputBlock", "element", InputElement.class);
  }

  /**
   * Returns whether changing the element sends a block_actions payload immediately.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Boolean> getDispatchAction() {
    return TypedFields.optional(fields, "InputBlock", "dispatch_action", Boolean.class);
  }

  /**
   * Returns helper text shown below the input.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<PlainText> getHint() {
    return TypedFields.optionalText(fields, "InputBlock", "hint", PlainText.class);
  }

  /**
   * Returns whether the modal can be submitted when this input is empty.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Boolean> getOptional() {
    return TypedFields.optional(fields, "InputBlock", "optional", Boolean.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof InputBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link InputBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<InputBlock> {
    private final BuilderState state = new BuilderState("InputBlock", "input");

    private Builder() {}

    /**
     * Sets the label shown above the input.
     *
     * <p>Required. Slack allows at most 2000 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder label(String value) {
      state.set("label", WireObjects.text("plain_text", Objects.requireNonNull(value, "label")));
      return this;
    }

    /**
     * Sets the label shown above the input.
     *
     * <p>Required. Slack allows at most 2000 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder label(PlainText value) {
      state.set("label", value);
      return this;
    }

    /**
     * Sets the input element that collects the user's value.
     *
     * <p>Required.
     *
     * @param value nested {@link InputElement}
     * @return this builder
     */
    public Builder element(InputElement value) {
      state.set("element", value);
      return this;
    }

    /**
     * Sets whether changing the element sends a block_actions payload immediately.
     *
     * @param value value for Slack's {@code dispatch_action} field
     * @return this builder
     */
    public Builder dispatchAction(boolean value) {
      state.set("dispatch_action", value);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Sets helper text shown below the input.
     *
     * <p>Slack allows at most 2000 characters. The string is sent as a {@code plain_text} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder hint(String value) {
      state.set("hint", WireObjects.text("plain_text", Objects.requireNonNull(value, "hint")));
      return this;
    }

    /**
     * Sets helper text shown below the input.
     *
     * <p>Slack allows at most 2000 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder hint(PlainText value) {
      state.set("hint", value);
      return this;
    }

    /**
     * Sets whether the modal can be submitted when this input is empty.
     *
     * @param value value for Slack's {@code optional} field
     * @return this builder
     */
    public Builder optional(boolean value) {
      state.set("optional", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link InputBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public InputBlock build() {
      return state.build(InputBlock::new);
    }
  }
}
