// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.List;
import java.util.Map;

/**
 * A titled sequence of task cards.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code title}, {@code tasks}.
 *   <li>Task IDs must be unique within a plan.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/plan-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class PlanBlock implements Block {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private PlanBlock(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the plan title.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public String getTitle() {
    return TypedFields.required(fields, "PlanBlock", "title", String.class);
  }

  /**
   * Returns task cards in display order.
   *
   * @return the values in order, or an empty list when none were set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public List<TaskCardBlock> getTasks() {
    return TypedFields.list(fields, "PlanBlock", "tasks", TaskCardBlock.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof PlanBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link PlanBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<PlanBlock> {
    private final BuilderState state = new BuilderState("PlanBlock", "plan");

    private Builder() {}

    /**
     * Sets the plan title.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code title} field
     * @return this builder
     */
    public Builder title(String value) {
      state.set("title", value);
      return this;
    }

    /**
     * Adds task cards in display order.
     *
     * <p>Required. Slack allows at most 50 items. Each call appends to any values already added.
     *
     * @param values {@link TaskCardBlock} values appended in order
     * @return this builder
     */
    public Builder tasks(TaskCardBlock... values) {
      state.append("tasks", (Object[]) values);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link PlanBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public PlanBlock build() {
      return state.build(PlanBlock::new, wire -> WireObjects.withoutItemTypes(wire, "tasks"));
    }
  }
}
