// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.block;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.element.Element;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Text;
import java.util.Map;
import java.util.Objects;

/**
 * Text, a grid of fields, or both, with an optional accessory element.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Provide text, fields, or both.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/section-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class SectionBlock implements Block {
  private final Map<String, Object> values;
  private final int hash;

  private SectionBlock(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof SectionBlock that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link SectionBlock}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<SectionBlock> {
    private final BuilderState state = new BuilderState("SectionBlock", "section");

    private Builder() {}

    /**
     * Sets the main text of the section.
     *
     * <p>Slack allows at most 3000 characters. The string is sent as a {@code mrkdwn} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the main text of the section.
     *
     * <p>Slack allows at most 3000 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder text(Text value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the main text of the section.
     *
     * <p>Slack allows at most 3000 characters. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder markdownText(String value) {
      text(value);
      return this;
    }

    /**
     * Adds section fields, shown in a two-column grid, in display order.
     *
     * <p>Slack allows at most 10 items, each at most 2000 characters. Each call appends to any
     * values already added.
     *
     * @param values {@link Text} objects appended in order
     * @return this builder
     */
    public Builder fields(Text... values) {
      state.append("fields", (Object[]) values);
      return this;
    }

    /**
     * Adds section fields, shown in a two-column grid, in display order.
     *
     * <p>Slack allows at most 10 items, each at most 2000 characters. Each string is sent as a
     * {@code mrkdwn} text object.
     *
     * @param values strings appended in order
     * @return this builder
     */
    public Builder markdownFields(String... values) {
      Objects.requireNonNull(values, "fields");
      for (String value : values) {
        state.append("fields", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "fields")));
      }
      return this;
    }

    /**
     * Sets the element displayed beside the section text.
     *
     * @param value nested {@link Element}
     * @return this builder
     */
    public Builder accessory(Element value) {
      state.set("accessory", value);
      return this;
    }

    /**
     * Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a
     * stable value when you need to find the block again.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code block_id} field
     * @return this builder
     */
    public Builder blockId(String value) {
      state.set("block_id", value);
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link SectionBlock}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public SectionBlock build() {
      return state.build(SectionBlock::new);
    }
  }
}
