// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.block;

import java.util.Optional;

/** States supported by task card blocks. */
public enum TaskStatus {
  /** The task has not started. */
  PENDING("pending"),

  /** The task is running. */
  IN_PROGRESS("in_progress"),

  /** The task finished successfully. */
  COMPLETE("complete"),

  /** The task failed. */
  ERROR("error");

  private final String wireValue;

  TaskStatus(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }

  /**
   * Finds the constant for a Slack JSON value.
   *
   * @param wireValue the value Slack uses in JSON
   * @return the matching constant, or an empty optional for an unknown value
   */
  public static Optional<TaskStatus> fromWireValue(String wireValue) {
    for (TaskStatus constant : values()) {
      if (constant.wireValue.equals(wireValue)) {
        return Optional.of(constant);
      }
    }
    return Optional.empty();
  }
}
