// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

/** Horizontal alignment for table columns. */
public enum ColumnAlign {
  /** Align cell content to the left. */
  LEFT("left"),

  /** Center cell content. */
  CENTER("center"),

  /** Align cell content to the right. */
  RIGHT("right");

  private final String wireValue;

  ColumnAlign(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }
}
