// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.object;

import java.util.Optional;

/** Horizontal alignment for table columns. */
public enum ColumnAlign {
  /** Align cell content to the left. */
  LEFT("left"),

  /** Center cell content. */
  CENTER("center"),

  /** Align cell content to the right. */
  RIGHT("right");

  private final String wireValue;

  ColumnAlign(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }

  /**
   * Finds the constant for a Slack JSON value.
   *
   * @param wireValue the value Slack uses in JSON
   * @return the matching constant, or an empty optional for an unknown value
   */
  public static Optional<ColumnAlign> fromWireValue(String wireValue) {
    for (ColumnAlign constant : values()) {
      if (constant.wireValue.equals(wireValue)) {
        return Optional.of(constant);
      }
    }
    return Optional.empty();
  }
}
