// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import java.util.Map;
import java.util.Objects;

/**
 * Alignment and wrapping settings for one table column.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/table-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class ColumnSettings implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private ColumnSettings(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof ColumnSettings that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link ColumnSettings}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<ColumnSettings> {
    private final BuilderState state = new BuilderState("ColumnSettings", "");

    private Builder() {}

    /**
     * Sets how cell content in the column is aligned.
     *
     * @param value value for Slack's {@code align} field
     * @return this builder
     */
    public Builder align(ColumnAlign value) {
      state.set("align", Objects.requireNonNull(value, "align").wireValue());
      return this;
    }

    /**
     * Sets whether long cell content wraps instead of being truncated.
     *
     * @param value value for Slack's {@code is_wrapped} field
     * @return this builder
     */
    public Builder isWrapped(boolean value) {
      state.set("is_wrapped", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link ColumnSettings}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public ColumnSettings build() {
      return state.build(ColumnSettings::new);
    }
  }
}
