// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.element.ButtonStyle;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.Map;
import java.util.Objects;

/**
 * A dialog that asks users to confirm an action before it is sent.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code title}, {@code text}, {@code confirm}, {@code deny}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/composition-objects/confirmation-dialog-object">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class Confirmation implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private Confirmation(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof Confirmation that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link Confirmation}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<Confirmation> {
    private final BuilderState state = new BuilderState("Confirmation", "");

    private Builder() {}

    /**
     * Sets the dialog title.
     *
     * <p>Required. Slack allows at most 100 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder title(String value) {
      state.set("title", WireObjects.text("plain_text", Objects.requireNonNull(value, "title")));
      return this;
    }

    /**
     * Sets the dialog title.
     *
     * <p>Required. Slack allows at most 100 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder title(PlainText value) {
      state.set("title", value);
      return this;
    }

    /**
     * Sets the explanatory text in the dialog body.
     *
     * <p>Required. Slack allows at most 300 characters. The string is sent as a {@code mrkdwn} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("mrkdwn", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the explanatory text in the dialog body.
     *
     * <p>Required. Slack allows at most 300 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder text(Text value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the explanatory text in the dialog body.
     *
     * <p>Required. Slack allows at most 300 characters. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder markdownText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets the label of the button that confirms the action.
     *
     * <p>Required. Slack allows at most 30 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder confirm(String value) {
      state.set(
          "confirm", WireObjects.text("plain_text", Objects.requireNonNull(value, "confirm")));
      return this;
    }

    /**
     * Sets the label of the button that confirms the action.
     *
     * <p>Required. Slack allows at most 30 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder confirm(PlainText value) {
      state.set("confirm", value);
      return this;
    }

    /**
     * Sets the label of the button that cancels the action.
     *
     * <p>Required. Slack allows at most 30 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder deny(String value) {
      state.set("deny", WireObjects.text("plain_text", Objects.requireNonNull(value, "deny")));
      return this;
    }

    /**
     * Sets the label of the button that cancels the action.
     *
     * <p>Required. Slack allows at most 30 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder deny(PlainText value) {
      state.set("deny", value);
      return this;
    }

    /**
     * Sets the emphasis of the confirm button.
     *
     * @param value value for Slack's {@code style} field
     * @return this builder
     */
    public Builder style(ButtonStyle value) {
      state.set("style", Objects.requireNonNull(value, "style").wireValue());
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link Confirmation}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public Confirmation build() {
      return state.build(Confirmation::new);
    }
  }
}
