// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import java.util.Map;

/**
 * Limits which conversations a conversation menu offers.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Set at least one filter.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/composition-objects/conversation-filter-object">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class ConversationFilter implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private ConversationFilter(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ConversationFilter that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link ConversationFilter}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<ConversationFilter> {
    private final BuilderState state = new BuilderState("ConversationFilter", "");

    private Builder() {}

    /**
     * Adds conversation types to offer: im, mpim, private, or public.
     *
     * <p>Each call appends to any values already added.
     *
     * @param values values appended in order
     * @return this builder
     */
    public Builder include(String... values) {
      state.append("include", (Object[]) values);
      return this;
    }

    /**
     * Sets whether externally shared channels are excluded.
     *
     * @param value value for Slack's {@code exclude_external_shared_channels} field
     * @return this builder
     */
    public Builder excludeExternalSharedChannels(boolean value) {
      state.set("exclude_external_shared_channels", value);
      return this;
    }

    /**
     * Sets whether bot users are excluded.
     *
     * @param value value for Slack's {@code exclude_bot_users} field
     * @return this builder
     */
    public Builder excludeBotUsers(boolean value) {
      state.set("exclude_bot_users", value);
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link ConversationFilter}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public ConversationFilter build() {
      return state.build(ConversationFilter::new);
    }
  }
}
