// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.List;
import java.util.Map;

/**
 * A named series of chart data points.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code name}, {@code data}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/data-visualization-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class DataSeries implements SlackObject {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private DataSeries(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the series name shown in the legend.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public String getName() {
    return TypedFields.required(fields, "DataSeries", "name", String.class);
  }

  /**
   * Returns data points in axis-category order.
   *
   * @return the values in order, or an empty list when none were set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public List<DataPoint> getData() {
    return TypedFields.list(fields, "DataSeries", "data", DataPoint.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof DataSeries that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link DataSeries}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<DataSeries> {
    private final BuilderState state = new BuilderState("DataSeries", "");

    private Builder() {}

    /**
     * Sets the series name shown in the legend.
     *
     * <p>Required. Slack allows at most 20 characters.
     *
     * @param value value for Slack's {@code name} field
     * @return this builder
     */
    public Builder name(String value) {
      state.set("name", value);
      return this;
    }

    /**
     * Adds data points in axis-category order.
     *
     * <p>Required. Must contain between 1 and 20 items. Each call appends to any values already
     * added.
     *
     * @param values {@link DataPoint} values appended in order
     * @return this builder
     */
    public Builder data(DataPoint... values) {
      state.append("data", (Object[]) values);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link DataSeries}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public DataSeries build() {
      return state.build(DataSeries::new);
    }
  }
}
