// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.Map;
import java.util.Objects;

/**
 * One button of a feedback buttons element.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}, {@code value}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/feedback-buttons-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class FeedbackButton implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private FeedbackButton(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof FeedbackButton that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link FeedbackButton}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<FeedbackButton> {
    private final BuilderState state = new BuilderState("FeedbackButton", "");

    private Builder() {}

    /**
     * Sets the button label.
     *
     * <p>Required. Slack allows at most 75 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("plain_text", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the button label.
     *
     * <p>Required. Slack allows at most 75 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder text(PlainText value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the button label.
     *
     * <p>Required. Slack allows at most 75 characters. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder plainText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets the application-defined value sent in interaction payloads.
     *
     * <p>Required. Slack allows at most 2000 characters.
     *
     * @param value value for Slack's {@code value} field
     * @return this builder
     */
    public Builder value(String value) {
      state.set("value", value);
      return this;
    }

    /**
     * Sets the label read by screen readers in place of the visible text.
     *
     * <p>Slack allows at most 75 characters.
     *
     * @param value value for Slack's {@code accessibility_label} field
     * @return this builder
     */
    public Builder accessibilityLabel(String value) {
      state.set("accessibility_label", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link FeedbackButton}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public FeedbackButton build() {
      return state.build(FeedbackButton::new);
    }
  }
}
