// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import java.util.Map;

/**
 * A line chart for a data visualization block.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code series}, {@code axisConfig}.
 *   <li>Every series needs exactly one data point for each axis category.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/data-visualization-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class LineChart implements Chart {
  private final Map<String, Object> values;
  private final int hash;

  private LineChart(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof LineChart that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link LineChart}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<LineChart> {
    private final BuilderState state = new BuilderState("LineChart", "line");

    private Builder() {}

    /**
     * Adds data series in display order. Series names must be unique.
     *
     * <p>Required. Must contain between 1 and 12 items. Each call appends to any values already
     * added.
     *
     * @param values {@link DataSeries} values appended in order
     * @return this builder
     */
    public Builder series(DataSeries... values) {
      state.append("series", (Object[]) values);
      return this;
    }

    /**
     * Sets the axis categories and labels. Every series needs exactly one point per category.
     *
     * <p>Required.
     *
     * @param value nested {@link AxisConfig}
     * @return this builder
     */
    public Builder axisConfig(AxisConfig value) {
      state.set("axis_config", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link LineChart}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public LineChart build() {
      return state.build(LineChart::new);
    }
  }
}
