// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.composition.TextObject;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.block.ContextElement;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * A mrkdwn text composition object.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/composition-objects/text-object">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class MarkdownText extends TextObject implements Text, ContextElement {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private MarkdownText(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Creates and validates mrkdwn text in one call.
   *
   * @param text mrkdwn content
   * @return an immutable MarkdownText
   * @throws ValidationException if the value breaks a Block Kit rule
   */
  public static MarkdownText of(String text) {
    return builder().text(text).build();
  }

  /**
   * Returns whether Slack leaves URLs, mentions, and channel names unlinked.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Boolean> getVerbatim() {
    return TypedFields.optional(fields, "MarkdownText", "verbatim", Boolean.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  /**
   * Returns the Slack text representation type.
   *
   * @return Slack wire type
   */
  @Override
  public String getType() {
    return (String) Objects.requireNonNull(values.get("type"));
  }

  /**
   * Returns the text content.
   *
   * @return text content
   */
  @Override
  public String getText() {
    return (String) Objects.requireNonNull(values.get("text"));
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof MarkdownText that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link MarkdownText}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<MarkdownText> {
    private final BuilderState state = new BuilderState("MarkdownText", "mrkdwn");

    private Builder() {}

    /**
     * Sets the mrkdwn-formatted text content.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code text} field
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets whether Slack leaves URLs, mentions, and channel names unlinked.
     *
     * @param value value for Slack's {@code verbatim} field
     * @return this builder
     */
    public Builder verbatim(boolean value) {
      state.set("verbatim", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link MarkdownText}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public MarkdownText build() {
      return state.build(MarkdownText::new);
    }
  }
}
