// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.Map;
import java.util.Objects;

/**
 * A selectable option for menus, checkboxes, radio buttons, and overflow menus.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}, {@code value}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/composition-objects/option-object">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class Option implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private Option(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Starts an option builder with its required label and value.
   *
   * @param text visible option label
   * @param value application-defined value
   * @return a new builder
   */
  public static Builder builder(String text, String value) {
    return builder().text(text).value(value);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof Option that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link Option}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<Option> {
    private final BuilderState state = new BuilderState("Option", "");

    private Builder() {}

    /**
     * Sets the option label shown to users.
     *
     * <p>Required. Slack allows at most 75 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("plain_text", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the option label shown to users.
     *
     * <p>Required. Slack allows at most 75 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder text(Text value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the option label shown to users.
     *
     * <p>Required. Slack allows at most 75 characters. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder plainText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets the value sent in interaction payloads when this option is chosen.
     *
     * <p>Required. Slack allows at most 150 characters.
     *
     * @param value value for Slack's {@code value} field
     * @return this builder
     */
    public Builder value(String value) {
      state.set("value", value);
      return this;
    }

    /**
     * Sets supporting text shown below the label. Only rendered by checkboxes and radio buttons.
     *
     * <p>Slack allows at most 75 characters. The string is sent as a {@code plain_text} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder description(String value) {
      state.set(
          "description",
          WireObjects.text("plain_text", Objects.requireNonNull(value, "description")));
      return this;
    }

    /**
     * Sets supporting text shown below the label. Only rendered by checkboxes and radio buttons.
     *
     * <p>Slack allows at most 75 characters.
     *
     * @param value a {@link Text} object
     * @return this builder
     */
    public Builder description(Text value) {
      state.set("description", value);
      return this;
    }

    /**
     * Sets a URL loaded in the user's browser when an overflow menu option is chosen.
     *
     * <p>Slack allows at most 3000 characters.
     *
     * @param value value for Slack's {@code url} field
     * @return this builder
     */
    public Builder url(String value) {
      state.set("url", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link Option}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public Option build() {
      return state.build(Option::new);
    }
  }
}
