// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * A labelled group of options in a static select menu.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code label}, {@code options}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/composition-objects/option-group-object">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class OptionGroup implements SlackObject {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private OptionGroup(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the group heading.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public PlainText getLabel() {
    return TypedFields.requiredText(fields, "OptionGroup", "label", PlainText.class);
  }

  /**
   * Returns selectable options in display order.
   *
   * @return the values in order, or an empty list when none were set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public List<Option> getOptions() {
    return TypedFields.list(fields, "OptionGroup", "options", Option.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof OptionGroup that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link OptionGroup}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<OptionGroup> {
    private final BuilderState state = new BuilderState("OptionGroup", "");

    private Builder() {}

    /**
     * Sets the group heading.
     *
     * <p>Required. Slack allows at most 75 characters. The string is sent as a {@code plain_text}
     * text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder label(String value) {
      state.set("label", WireObjects.text("plain_text", Objects.requireNonNull(value, "label")));
      return this;
    }

    /**
     * Sets the group heading.
     *
     * <p>Required. Slack allows at most 75 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder label(PlainText value) {
      state.set("label", value);
      return this;
    }

    /**
     * Adds selectable options in display order.
     *
     * <p>Required. Must contain between 1 and 100 items. Each call appends to any values already
     * added.
     *
     * @param values {@link Option} values appended in order
     * @return this builder
     */
    public Builder options(Option... values) {
      state.append("options", (Object[]) values);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link OptionGroup}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public OptionGroup build() {
      return state.build(OptionGroup::new);
    }
  }
}
