// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import java.util.Map;

/**
 * A pie chart for a data visualization block.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code segments}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/data-visualization-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class PieChart implements Chart {
  private final Map<String, Object> values;
  private final int hash;

  private PieChart(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof PieChart that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link PieChart}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<PieChart> {
    private final BuilderState state = new BuilderState("PieChart", "pie");

    private Builder() {}

    /**
     * Adds pie segments in display order.
     *
     * <p>Required. Must contain between 1 and 12 items. Each call appends to any values already
     * added.
     *
     * @param values {@link ChartSegment} values appended in order
     * @return this builder
     */
    public Builder segments(ChartSegment... values) {
      state.append("segments", (Object[]) values);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link PieChart}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public PieChart build() {
      return state.build(PieChart::new);
    }
  }
}
