// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.block.DataTableCell;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import java.util.Map;

/**
 * A numeric data table cell with display text.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code value}, {@code text}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/data-table-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class RawNumber implements DataTableCell {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private RawNumber(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the numeric value used for sorting.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Number getValue() {
    return TypedFields.required(fields, "RawNumber", "value", Number.class);
  }

  /**
   * Returns the formatted text displayed for the number, such as 1,234.5.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public String getText() {
    return TypedFields.required(fields, "RawNumber", "text", String.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof RawNumber that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link RawNumber}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<RawNumber> {
    private final BuilderState state = new BuilderState("RawNumber", "raw_number");

    private Builder() {}

    /**
     * Sets the numeric value used for sorting.
     *
     * <p>Required. Whole numbers are sent without a decimal point.
     *
     * @param value whole-number value
     * @return this builder
     */
    public Builder value(long value) {
      state.set("value", value);
      return this;
    }

    /**
     * Sets the numeric value used for sorting.
     *
     * <p>Required. Prefer {@link #value(long)} for whole numbers.
     *
     * @param value decimal value
     * @return this builder
     */
    public Builder value(double value) {
      state.set("value", value);
      return this;
    }

    /**
     * Sets the formatted text displayed for the number, such as 1,234.5.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code text} field
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link RawNumber}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public RawNumber build() {
      return state.build(RawNumber::new);
    }
  }
}
