// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import io.github.nicklambourne.slackblocks.SlackObject;

/**
 * An inline rich text element: text, a link, an emoji, or a channel, user, or user group mention.
 *
 * <p>Implemented by {@link RichTextChannel}, {@link RichTextEmoji}, {@link RichTextLink}, {@link
 * RichTextText}, {@link RichTextUser}, {@link RichTextUserGroup}.
 */
public interface RichTextSectionElement extends SlackObject {}
