// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.OptionalInt;

/**
 * A bulleted or numbered list inside rich text.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code style}, {@code elements}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/rich-text-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class RichTextList implements RichTextBlockElement {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private RichTextList(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns whether the list is bulleted or numbered.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public RichTextListStyle getStyle() {
    return TypedFields.requiredEnum(
        fields, "RichTextList", "style", RichTextListStyle::fromWireValue);
  }

  /**
   * Returns list items, one rich text section per item.
   *
   * @return the values in order, or an empty list when none were set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public List<RichTextSection> getElements() {
    return TypedFields.list(fields, "RichTextList", "elements", RichTextSection.class);
  }

  /**
   * Returns the list's indentation level.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public OptionalInt getIndent() {
    return TypedFields.optionalInt(fields, "RichTextList", "indent");
  }

  /**
   * Returns the number of items to skip when numbering an ordered list.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public OptionalInt getOffset() {
    return TypedFields.optionalInt(fields, "RichTextList", "offset");
  }

  /**
   * Returns the width of the left border, in pixels.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public OptionalInt getBorder() {
    return TypedFields.optionalInt(fields, "RichTextList", "border");
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof RichTextList that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link RichTextList}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<RichTextList> {
    private final BuilderState state = new BuilderState("RichTextList", "rich_text_list");

    private Builder() {}

    /**
     * Sets whether the list is bulleted or numbered.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code style} field
     * @return this builder
     */
    public Builder style(RichTextListStyle value) {
      state.set("style", Objects.requireNonNull(value, "style").wireValue());
      return this;
    }

    /**
     * Adds list items, one rich text section per item.
     *
     * <p>Required. Each call appends to any values already added.
     *
     * @param values {@link RichTextSection} values appended in order
     * @return this builder
     */
    public Builder elements(RichTextSection... values) {
      state.append("elements", (Object[]) values);
      return this;
    }

    /**
     * Sets the list's indentation level.
     *
     * <p>Must be between 0 and 8.
     *
     * @param value value for Slack's {@code indent} field
     * @return this builder
     */
    public Builder indent(int value) {
      state.set("indent", value);
      return this;
    }

    /**
     * Sets the number of items to skip when numbering an ordered list.
     *
     * <p>Must be at least 0.
     *
     * @param value value for Slack's {@code offset} field
     * @return this builder
     */
    public Builder offset(int value) {
      state.set("offset", value);
      return this;
    }

    /**
     * Sets the width of the left border, in pixels.
     *
     * <p>Must be between 0 and 1.
     *
     * @param value value for Slack's {@code border} field
     * @return this builder
     */
    public Builder border(int value) {
      state.set("border", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link RichTextList}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public RichTextList build() {
      return state.build(RichTextList::new);
    }
  }
}
