// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.Map;

/**
 * A channel mention inside rich text.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code channelId}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/rich-text-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class RichTextChannel implements RichTextSectionElement {
  private final Map<String, Object> values;
  private final int hash;

  private RichTextChannel(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof RichTextChannel that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link RichTextChannel}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<RichTextChannel> {
    private final BuilderState state = new BuilderState("RichTextChannel", "channel");

    private Builder() {}

    /**
     * Sets the ID of the mentioned channel.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code channel_id} field
     * @return this builder
     */
    public Builder channelId(String value) {
      state.set("channel_id", value);
      return this;
    }

    /**
     * Sets the mention style.
     *
     * <p>Replaces any style flags already set.
     *
     * @param value the complete text style
     * @return this builder
     */
    public Builder style(RichTextStyle value) {
      state.set("style", value);
      return this;
    }

    /**
     * Sets whether the {@code bold} style is applied.
     *
     * @param value whether to apply the style
     * @return this builder
     */
    public Builder bold(boolean value) {
      state.merge("style", "bold", value);
      return this;
    }

    /**
     * Sets whether the {@code italic} style is applied.
     *
     * @param value whether to apply the style
     * @return this builder
     */
    public Builder italic(boolean value) {
      state.merge("style", "italic", value);
      return this;
    }

    /**
     * Sets whether the {@code strike} style is applied.
     *
     * @param value whether to apply the style
     * @return this builder
     */
    public Builder strike(boolean value) {
      state.merge("style", "strike", value);
      return this;
    }

    /**
     * Sets whether the {@code highlight} style is applied.
     *
     * @param value whether to apply the style
     * @return this builder
     */
    public Builder highlight(boolean value) {
      state.merge("style", "highlight", value);
      return this;
    }

    /**
     * Sets whether the {@code client_highlight} style is applied.
     *
     * @param value whether to apply the style
     * @return this builder
     */
    public Builder clientHighlight(boolean value) {
      state.merge("style", "client_highlight", value);
      return this;
    }

    /**
     * Sets whether the {@code unlink} style is applied.
     *
     * @param value whether to apply the style
     * @return this builder
     */
    public Builder unlink(boolean value) {
      state.merge("style", "unlink", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link RichTextChannel}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public RichTextChannel build() {
      return state.build(RichTextChannel::new);
    }
  }
}
