// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import java.util.Optional;

/** Marker styles for rich text lists. */
public enum RichTextListStyle {
  /** An unordered, bulleted list. */
  BULLET("bullet"),

  /** A numbered list. */
  ORDERED("ordered");

  private final String wireValue;

  RichTextListStyle(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }

  /**
   * Finds the constant for a Slack JSON value.
   *
   * @param wireValue the value Slack uses in JSON
   * @return the matching constant, or an empty optional for an unknown value
   */
  public static Optional<RichTextListStyle> fromWireValue(String wireValue) {
    for (RichTextListStyle constant : values()) {
      if (constant.wireValue.equals(wireValue)) {
        return Optional.of(constant);
      }
    }
    return Optional.empty();
  }
}
