// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

/** Marker styles for rich text lists. */
public enum RichTextListStyle {
  /** An unordered, bulleted list. */
  BULLET("bullet"),

  /** A numbered list. */
  ORDERED("ordered");

  private final String wireValue;

  RichTextListStyle(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }
}
