// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import java.util.Map;

/**
 * A Slack-provided icon, referenced by name.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/card-block">Slack reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class SlackIcon implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private SlackIcon(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof SlackIcon that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link SlackIcon}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<SlackIcon> {
    private final BuilderState state = new BuilderState("SlackIcon", "icon");

    private Builder() {}

    /**
     * Sets the name of the Slack-provided icon, such as rocket.
     *
     * @param value value for Slack's {@code name} field
     * @return this builder
     */
    public Builder name(String value) {
      state.set("name", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link SlackIcon}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public SlackIcon build() {
      return state.build(SlackIcon::new);
    }
  }
}
