// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import io.github.nicklambourne.slackblocks.SlackObject;

/**
 * A Slack text composition object: plain text or mrkdwn.
 *
 * <p>Implemented by {@link MarkdownText}, {@link PlainText}.
 */
public interface Text extends SlackObject {}
