// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.object;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import java.util.Map;

/**
 * A linked source cited by a task card.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code url}, {@code text}.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/blocks/task-card-block">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class UrlSource implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private UrlSource(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof UrlSource that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link UrlSource}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<UrlSource> {
    private final BuilderState state = new BuilderState("UrlSource", "url");

    private Builder() {}

    /**
     * Sets the source URL.
     *
     * <p>Required. Must be between 1 and 3000 characters.
     *
     * @param value value for Slack's {@code url} field
     * @return this builder
     */
    public Builder url(String value) {
      state.set("url", value);
      return this;
    }

    /**
     * Sets the source link text.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code text} field
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link UrlSource}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public UrlSource build() {
      return state.build(UrlSource::new);
    }
  }
}
