// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

/** Visual emphasis for buttons and confirmation dialogs. */
public enum ButtonStyle {
  /** Green emphasis for the affirmative action. */
  PRIMARY("primary"),

  /** Red emphasis for destructive actions. */
  DANGER("danger");

  private final String wireValue;

  ButtonStyle(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }
}
