// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Confirmation;
import io.github.nicklambourne.slackblocks.object.ConversationFilter;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;

/**
 * A menu for selecting one conversation.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code actionId}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/select-menu-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class ConversationSelectElement extends BlockElement implements InputElement {
  private final Map<String, Object> values;
  private final int hash;

  private ConversationSelectElement(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ConversationSelectElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /**
   * Fluent builder for {@link ConversationSelectElement}. Builders are mutable and not thread-safe.
   */
  public static final class Builder implements Buildable<ConversationSelectElement> {
    private final BuilderState state =
        new BuilderState("ConversationSelectElement", "conversations_select");

    private Builder() {}

    /**
     * Sets the identifier Slack returns in interaction payloads when a user acts on this element.
     * It must be unique among the elements of its block.
     *
     * <p>Required. Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code action_id} field
     * @return this builder
     */
    public Builder actionId(String value) {
      state.set("action_id", value);
      return this;
    }

    /**
     * Sets the conversation ID selected when the menu loads.
     *
     * @param value value for Slack's {@code initial_conversation} field
     * @return this builder
     */
    public Builder initialConversation(String value) {
      state.set("initial_conversation", value);
      return this;
    }

    /**
     * Sets whether the menu pre-selects the conversation the user is viewing.
     *
     * @param value value for Slack's {@code default_to_current_conversation} field
     * @return this builder
     */
    public Builder defaultToCurrentConversation(boolean value) {
      state.set("default_to_current_conversation", value);
      return this;
    }

    /**
     * Sets which conversation types the menu offers.
     *
     * @param value nested {@link ConversationFilter}
     * @return this builder
     */
    public Builder filter(ConversationFilter value) {
      state.set("filter", value);
      return this;
    }

    /**
     * Sets whether the selected conversation receives a response URL in the view submission
     * payload. Only valid in modals.
     *
     * @param value value for Slack's {@code response_url_enabled} field
     * @return this builder
     */
    public Builder responseUrlEnabled(boolean value) {
      state.set("response_url_enabled", value);
      return this;
    }

    /**
     * Sets a confirmation dialog shown before the action is sent.
     *
     * @param value nested {@link Confirmation}
     * @return this builder
     */
    public Builder confirm(Confirmation value) {
      state.set("confirm", value);
      return this;
    }

    /**
     * Sets whether the element receives focus when the view opens. Only one element per view may do
     * so.
     *
     * @param value value for Slack's {@code focus_on_load} field
     * @return this builder
     */
    public Builder focusOnLoad(boolean value) {
      state.set("focus_on_load", value);
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>Slack allows at most 150 characters. The string is sent as a {@code plain_text} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder placeholder(String value) {
      state.set(
          "placeholder",
          WireObjects.text("plain_text", Objects.requireNonNull(value, "placeholder")));
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>Slack allows at most 150 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder placeholder(PlainText value) {
      state.set("placeholder", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link ConversationSelectElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public ConversationSelectElement build() {
      return state.build(ConversationSelectElement::new);
    }
  }
}
