// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.element;

import io.github.nicklambourne.slackblocks.SlackObject;

/**
 * A validated interactive, visual, or input element nested inside a Slack block.
 *
 * <p>Implemented by {@link ButtonElement}, {@link ChannelMultiSelectElement}, {@link
 * ChannelSelectElement}, {@link CheckboxesElement}, {@link ConversationMultiSelectElement}, {@link
 * ConversationSelectElement}, {@link DatePickerElement}, {@link DateTimePickerElement}, {@link
 * EmailInputElement}, {@link ExternalMultiSelectElement}, {@link ExternalSelectElement}, {@link
 * FeedbackButtonsElement}, {@link FileInputElement}, {@link IconButtonElement}, {@link
 * ImageElement}, {@link NumberInputElement}, {@link OverflowElement}, {@link
 * PlainTextInputElement}, {@link RadioButtonsElement}, {@link RichTextInputElement}, {@link
 * StaticMultiSelectElement}, {@link StaticSelectElement}, {@link TimePickerElement}, {@link
 * UrlInputElement}, {@link UserMultiSelectElement}, {@link UserSelectElement}, {@link
 * WorkflowButtonElement}.
 */
public interface Element extends SlackObject {}
