// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Confirmation;
import io.github.nicklambourne.slackblocks.object.Option;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;

/**
 * A menu for selecting multiple options loaded from your app.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code actionId}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/multi-select-menu-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class ExternalMultiSelectElement extends BlockElement implements InputElement {
  private final Map<String, Object> values;
  private final int hash;

  private ExternalMultiSelectElement(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ExternalMultiSelectElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /**
   * Fluent builder for {@link ExternalMultiSelectElement}. Builders are mutable and not
   * thread-safe.
   */
  public static final class Builder implements Buildable<ExternalMultiSelectElement> {
    private final BuilderState state =
        new BuilderState("ExternalMultiSelectElement", "multi_external_select");

    private Builder() {}

    /**
     * Sets the identifier Slack returns in interaction payloads when a user acts on this element.
     * It must be unique among the elements of its block.
     *
     * <p>Required. Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code action_id} field
     * @return this builder
     */
    public Builder actionId(String value) {
      state.set("action_id", value);
      return this;
    }

    /**
     * Sets how many characters the user must type before Slack queries your options endpoint.
     *
     * @param value value for Slack's {@code min_query_length} field
     * @return this builder
     */
    public Builder minQueryLength(int value) {
      state.set("min_query_length", value);
      return this;
    }

    /**
     * Adds options that are selected when the element loads. Each must match an option in the
     * element.
     *
     * <p>Each call appends to any values already added.
     *
     * @param values {@link Option} values appended in order
     * @return this builder
     */
    public Builder initialOptions(Option... values) {
      state.append("initial_options", (Object[]) values);
      return this;
    }

    /**
     * Sets a confirmation dialog shown before the action is sent.
     *
     * @param value nested {@link Confirmation}
     * @return this builder
     */
    public Builder confirm(Confirmation value) {
      state.set("confirm", value);
      return this;
    }

    /**
     * Sets the maximum number of items a user can select.
     *
     * @param value value for Slack's {@code max_selected_items} field
     * @return this builder
     */
    public Builder maxSelectedItems(int value) {
      state.set("max_selected_items", value);
      return this;
    }

    /**
     * Sets whether the element receives focus when the view opens. Only one element per view may do
     * so.
     *
     * @param value value for Slack's {@code focus_on_load} field
     * @return this builder
     */
    public Builder focusOnLoad(boolean value) {
      state.set("focus_on_load", value);
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>Slack allows at most 150 characters. The string is sent as a {@code plain_text} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder placeholder(String value) {
      state.set(
          "placeholder",
          WireObjects.text("plain_text", Objects.requireNonNull(value, "placeholder")));
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>Slack allows at most 150 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder placeholder(PlainText value) {
      state.set("placeholder", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link ExternalMultiSelectElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public ExternalMultiSelectElement build() {
      return state.build(ExternalMultiSelectElement::new);
    }
  }
}
