// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.element;

import java.util.Optional;

/** Icons supported by icon buttons. */
public enum IconButtonIcon {
  /** A trash can, for delete actions. */
  TRASH("trash");

  private final String wireValue;

  IconButtonIcon(String wireValue) {
    this.wireValue = wireValue;
  }

  /**
   * Returns the value Slack expects in JSON.
   *
   * @return the wire value
   */
  public String wireValue() {
    return wireValue;
  }

  /**
   * Finds the constant for a Slack JSON value.
   *
   * @param wireValue the value Slack uses in JSON
   * @return the matching constant, or an empty optional for an unknown value
   */
  public static Optional<IconButtonIcon> fromWireValue(String wireValue) {
    for (IconButtonIcon constant : values()) {
      if (constant.wireValue.equals(wireValue)) {
        return Optional.of(constant);
      }
    }
    return Optional.empty();
  }
}
