// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.block.ContextActionsElement;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Confirmation;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;

/**
 * A button that shows an icon instead of text.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/icon-button-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class IconButtonElement extends BlockElement
    implements Element, ContextActionsElement {
  private final Map<String, Object> values;
  private final int hash;

  private IconButtonElement(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof IconButtonElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link IconButtonElement}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<IconButtonElement> {
    private final BuilderState state = new BuilderState("IconButtonElement", "icon_button");

    private Builder() {
      state.set("icon", "trash");
    }

    /**
     * Sets the text used as the button's accessible name.
     *
     * <p>Required. The string is sent as a {@code plain_text} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("plain_text", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the text used as the button's accessible name.
     *
     * <p>Required.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder text(PlainText value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the text used as the button's accessible name.
     *
     * <p>Required. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder plainText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets the icon shown on the button.
     *
     * @param value value for Slack's {@code icon} field
     * @return this builder
     */
    public Builder icon(IconButtonIcon value) {
      state.set("icon", Objects.requireNonNull(value, "icon").wireValue());
      return this;
    }

    /**
     * Sets the identifier Slack returns in interaction payloads when a user acts on this element.
     * It must be unique among the elements of its block.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code action_id} field
     * @return this builder
     */
    public Builder actionId(String value) {
      state.set("action_id", value);
      return this;
    }

    /**
     * Sets the application-defined value sent in interaction payloads.
     *
     * @param value value for Slack's {@code value} field
     * @return this builder
     */
    public Builder value(String value) {
      state.set("value", value);
      return this;
    }

    /**
     * Sets a confirmation dialog shown before the action is sent.
     *
     * @param value nested {@link Confirmation}
     * @return this builder
     */
    public Builder confirm(Confirmation value) {
      state.set("confirm", value);
      return this;
    }

    /**
     * Sets the label read by screen readers in place of the visible text.
     *
     * @param value value for Slack's {@code accessibility_label} field
     * @return this builder
     */
    public Builder accessibilityLabel(String value) {
      state.set("accessibility_label", value);
      return this;
    }

    /**
     * Adds the IDs of users who can see this button.
     *
     * <p>Slack allows at most 10 items. Each call appends to any values already added.
     *
     * @param values values appended in order
     * @return this builder
     */
    public Builder visibleToUserIds(String... values) {
      state.append("visible_to_user_ids", (Object[]) values);
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link IconButtonElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public IconButtonElement build() {
      return state.build(IconButtonElement::new);
    }
  }
}
