// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.block.ContextElement;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.object.SlackFile;
import java.util.Map;
import java.util.Optional;

/**
 * An image displayed inside a section, context, or card.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code altText}.
 *   <li>Provide exactly one of an image URL or a Slack file.
 * </ul>
 *
 * @see <a href="https://docs.slack.dev/reference/block-kit/block-elements/image-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class ImageElement extends BlockElement implements Element, ContextElement {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private ImageElement(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns a plain-text summary of the image or video for assistive technology.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public String getAltText() {
    return TypedFields.required(fields, "ImageElement", "alt_text", String.class);
  }

  /**
   * Returns the publicly accessible URL of the image. Cannot be combined with a Slack file.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<String> getImageUrl() {
    return TypedFields.optional(fields, "ImageElement", "image_url", String.class);
  }

  /**
   * Returns a file hosted in Slack as the image source. Cannot be combined with an image URL.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<SlackFile> getSlackFile() {
    return TypedFields.optional(fields, "ImageElement", "slack_file", SlackFile.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof ImageElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link ImageElement}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<ImageElement> {
    private final BuilderState state = new BuilderState("ImageElement", "image");

    private Builder() {}

    /**
     * Sets a plain-text summary of the image or video for assistive technology.
     *
     * <p>Required.
     *
     * @param value value for Slack's {@code alt_text} field
     * @return this builder
     */
    public Builder altText(String value) {
      state.set("alt_text", value);
      return this;
    }

    /**
     * Sets the publicly accessible URL of the image. Cannot be combined with a Slack file.
     *
     * @param value value for Slack's {@code image_url} field
     * @return this builder
     */
    public Builder imageUrl(String value) {
      state.set("image_url", value);
      return this;
    }

    /**
     * Sets a file hosted in Slack as the image source. Cannot be combined with an image URL.
     *
     * @param value nested {@link SlackFile}
     * @return this builder
     */
    public Builder slackFile(SlackFile value) {
      state.set("slack_file", value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link ImageElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public ImageElement build() {
      return state.build(ImageElement::new);
    }
  }
}
