// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.element;

/**
 * An element that can be placed in an input block.
 *
 * <p>Implemented by {@link ChannelMultiSelectElement}, {@link ChannelSelectElement}, {@link
 * CheckboxesElement}, {@link ConversationMultiSelectElement}, {@link ConversationSelectElement},
 * {@link DatePickerElement}, {@link DateTimePickerElement}, {@link EmailInputElement}, {@link
 * ExternalMultiSelectElement}, {@link ExternalSelectElement}, {@link FileInputElement}, {@link
 * NumberInputElement}, {@link PlainTextInputElement}, {@link RadioButtonsElement}, {@link
 * RichTextInputElement}, {@link StaticMultiSelectElement}, {@link StaticSelectElement}, {@link
 * TimePickerElement}, {@link UrlInputElement}, {@link UserMultiSelectElement}, {@link
 * UserSelectElement}.
 */
public interface InputElement extends Element {}
