// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.DispatchActionConfiguration;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.Map;
import java.util.Objects;

/**
 * An input that accepts whole or decimal numbers.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code actionId}.
 *   <li>The minimum value cannot exceed the maximum value.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/number-input-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class NumberInputElement extends BlockElement implements InputElement {
  private final Map<String, Object> values;
  private final int hash;

  private NumberInputElement(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof NumberInputElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link NumberInputElement}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<NumberInputElement> {
    private final BuilderState state = new BuilderState("NumberInputElement", "number_input");

    private Builder() {}

    /**
     * Sets the identifier Slack returns in interaction payloads when a user acts on this element.
     * It must be unique among the elements of its block.
     *
     * <p>Required. Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code action_id} field
     * @return this builder
     */
    public Builder actionId(String value) {
      state.set("action_id", value);
      return this;
    }

    /**
     * Sets whether the input accepts decimal numbers.
     *
     * @param value value for Slack's {@code is_decimal_allowed} field
     * @return this builder
     */
    public Builder isDecimalAllowed(boolean value) {
      state.set("is_decimal_allowed", value);
      return this;
    }

    /**
     * Sets the number present when the input loads, as a string such as 42 or 3.5.
     *
     * @param value value for Slack's {@code initial_value} field
     * @return this builder
     */
    public Builder initialValue(String value) {
      state.set("initial_value", value);
      return this;
    }

    /**
     * Sets the smallest accepted number.
     *
     * @param value value for Slack's {@code min_value} field
     * @return this builder
     */
    public Builder minValue(double value) {
      state.set("min_value", value);
      return this;
    }

    /**
     * Sets the largest accepted number.
     *
     * @param value value for Slack's {@code max_value} field
     * @return this builder
     */
    public Builder maxValue(double value) {
      state.set("max_value", value);
      return this;
    }

    /**
     * Sets which user interactions send a block_actions payload.
     *
     * @param value nested {@link DispatchActionConfiguration}
     * @return this builder
     */
    public Builder dispatchActionConfig(DispatchActionConfiguration value) {
      state.set("dispatch_action_config", value);
      return this;
    }

    /**
     * Sets whether the element receives focus when the view opens. Only one element per view may do
     * so.
     *
     * @param value value for Slack's {@code focus_on_load} field
     * @return this builder
     */
    public Builder focusOnLoad(boolean value) {
      state.set("focus_on_load", value);
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>The string is sent as a {@code plain_text} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder placeholder(String value) {
      state.set(
          "placeholder",
          WireObjects.text("plain_text", Objects.requireNonNull(value, "placeholder")));
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder placeholder(PlainText value) {
      state.set("placeholder", value);
      return this;
    }

    /**
     * Sets a forward-compatible wire field that does not yet have a named fluent method. Prefer the
     * named methods for normal Block Kit use.
     *
     * @param field Slack JSON field name
     * @param value wire-compatible value
     * @return this builder
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, value);
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link NumberInputElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public NumberInputElement build() {
      return state.build(NumberInputElement::new);
    }
  }
}
