// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Confirmation;
import io.github.nicklambourne.slackblocks.object.Option;
import io.github.nicklambourne.slackblocks.object.OptionGroup;
import io.github.nicklambourne.slackblocks.object.PlainText;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * A menu for selecting one option defined in the payload.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Use options or option groups, not both.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/select-menu-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class StaticSelectElement extends BlockElement implements InputElement {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private StaticSelectElement(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the identifier Slack returns in interaction payloads when a user acts on this element.
   * It must be unique among the elements of its block.
   *
   * @return the value
   * @throws IllegalStateException if the field is not set, or was set through a raw wire field to a
   *     value this type cannot represent
   */
  public String getActionId() {
    return TypedFields.required(fields, "StaticSelectElement", "action_id", String.class);
  }

  /**
   * Returns selectable options in display order.
   *
   * @return the values in order, or an empty list when none were set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public List<Option> getOptions() {
    return TypedFields.list(fields, "StaticSelectElement", "options", Option.class);
  }

  /**
   * Returns labelled groups of options in display order. Cannot be combined with ungrouped options.
   *
   * @return the values in order, or an empty list when none were set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public List<OptionGroup> getOptionGroups() {
    return TypedFields.list(fields, "StaticSelectElement", "option_groups", OptionGroup.class);
  }

  /**
   * Returns the option selected when the element loads. It must match an option in the element.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Option> getInitialOption() {
    return TypedFields.optional(fields, "StaticSelectElement", "initial_option", Option.class);
  }

  /**
   * Returns a confirmation dialog shown before the action is sent.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Confirmation> getConfirm() {
    return TypedFields.optional(fields, "StaticSelectElement", "confirm", Confirmation.class);
  }

  /**
   * Returns whether the element receives focus when the view opens. Only one element per view may
   * do so.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Boolean> getFocusOnLoad() {
    return TypedFields.optional(fields, "StaticSelectElement", "focus_on_load", Boolean.class);
  }

  /**
   * Returns the placeholder text shown before a value is chosen.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<PlainText> getPlaceholder() {
    return TypedFields.optionalText(fields, "StaticSelectElement", "placeholder", PlainText.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof StaticSelectElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link StaticSelectElement}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<StaticSelectElement> {
    private final BuilderState state = new BuilderState("StaticSelectElement", "static_select");

    private Builder() {}

    /**
     * Sets the identifier Slack returns in interaction payloads when a user acts on this element.
     * It must be unique among the elements of its block.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code action_id} field
     * @return this builder
     */
    public Builder actionId(String value) {
      state.set("action_id", value);
      return this;
    }

    /**
     * Adds selectable options in display order.
     *
     * <p>Slack allows at most 100 items. Each call appends to any values already added.
     *
     * @param values {@link Option} values appended in order
     * @return this builder
     */
    public Builder options(Option... values) {
      state.append("options", (Object[]) values);
      return this;
    }

    /**
     * Adds labelled groups of options in display order. Cannot be combined with ungrouped options.
     *
     * <p>Slack allows at most 100 items. Each call appends to any values already added.
     *
     * @param values {@link OptionGroup} values appended in order
     * @return this builder
     */
    public Builder optionGroups(OptionGroup... values) {
      state.append("option_groups", (Object[]) values);
      return this;
    }

    /**
     * Sets the option selected when the element loads. It must match an option in the element.
     *
     * @param value nested {@link Option}
     * @return this builder
     */
    public Builder initialOption(Option value) {
      state.set("initial_option", value);
      return this;
    }

    /**
     * Sets a confirmation dialog shown before the action is sent.
     *
     * @param value nested {@link Confirmation}
     * @return this builder
     */
    public Builder confirm(Confirmation value) {
      state.set("confirm", value);
      return this;
    }

    /**
     * Sets whether the element receives focus when the view opens. Only one element per view may do
     * so.
     *
     * @param value value for Slack's {@code focus_on_load} field
     * @return this builder
     */
    public Builder focusOnLoad(boolean value) {
      state.set("focus_on_load", value);
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>Slack allows at most 150 characters. The string is sent as a {@code plain_text} text
     * object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder placeholder(String value) {
      state.set(
          "placeholder",
          WireObjects.text("plain_text", Objects.requireNonNull(value, "placeholder")));
      return this;
    }

    /**
     * Sets the placeholder text shown before a value is chosen.
     *
     * <p>Slack allows at most 150 characters.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder placeholder(PlainText value) {
      state.set("placeholder", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link StaticSelectElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public StaticSelectElement build() {
      return state.build(StaticSelectElement::new);
    }
  }
}
