// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.element;

import com.google.gson.annotations.JsonAdapter;
import com.slack.api.model.block.element.BlockElement;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.TypedFields;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import io.github.nicklambourne.slackblocks.object.Confirmation;
import io.github.nicklambourne.slackblocks.object.PlainText;
import io.github.nicklambourne.slackblocks.object.Workflow;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * A button that starts a workflow through a link trigger.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Required: {@code text}, {@code workflow}.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/reference/block-kit/block-elements/workflow-button-element">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class WorkflowButtonElement extends BlockElement implements Element {
  private final Map<String, Object> values;
  private final Map<String, Object> fields;
  private final int hash;

  private WorkflowButtonElement(Map<String, Object> values, Map<String, Object> fields) {
    this.values = values;
    this.fields = fields;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the button label.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public PlainText getText() {
    return TypedFields.requiredText(fields, "WorkflowButtonElement", "text", PlainText.class);
  }

  /**
   * Returns the workflow started when the button is clicked.
   *
   * @return the value
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Workflow getWorkflow() {
    return TypedFields.required(fields, "WorkflowButtonElement", "workflow", Workflow.class);
  }

  /**
   * Returns the identifier Slack returns in interaction payloads when a user acts on this element.
   * It must be unique among the elements of its block.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<String> getActionId() {
    return TypedFields.optional(fields, "WorkflowButtonElement", "action_id", String.class);
  }

  /**
   * Returns a confirmation dialog shown before the action is sent.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<Confirmation> getConfirm() {
    return TypedFields.optional(fields, "WorkflowButtonElement", "confirm", Confirmation.class);
  }

  /**
   * Returns the button's emphasis. Omit it for the default neutral style.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<ButtonStyle> getStyle() {
    return TypedFields.optionalEnum(
        fields, "WorkflowButtonElement", "style", ButtonStyle::fromWireValue);
  }

  /**
   * Returns the label read by screen readers in place of the visible text.
   *
   * @return the value, or an empty optional when it was not set
   * @throws IllegalStateException if the field was set through a raw wire field to a value this
   *     type cannot represent
   */
  public Optional<String> getAccessibilityLabel() {
    return TypedFields.optional(
        fields, "WorkflowButtonElement", "accessibility_label", String.class);
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof WorkflowButtonElement that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link WorkflowButtonElement}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<WorkflowButtonElement> {
    private final BuilderState state = new BuilderState("WorkflowButtonElement", "workflow_button");

    private Builder() {}

    /**
     * Sets the button label.
     *
     * <p>Required. The string is sent as a {@code plain_text} text object.
     *
     * @param value text content
     * @return this builder
     */
    public Builder text(String value) {
      state.set("text", WireObjects.text("plain_text", Objects.requireNonNull(value, "text")));
      return this;
    }

    /**
     * Sets the button label.
     *
     * <p>Required.
     *
     * @param value a {@link PlainText} object
     * @return this builder
     */
    public Builder text(PlainText value) {
      state.set("text", value);
      return this;
    }

    /**
     * Sets the button label.
     *
     * <p>Required. Equivalent to {@link #text(String)}.
     *
     * @param value text content
     * @return this builder
     */
    public Builder plainText(String value) {
      text(value);
      return this;
    }

    /**
     * Sets the workflow started when the button is clicked.
     *
     * <p>Required.
     *
     * @param value nested {@link Workflow}
     * @return this builder
     */
    public Builder workflow(Workflow value) {
      state.set("workflow", value);
      return this;
    }

    /**
     * Sets the identifier Slack returns in interaction payloads when a user acts on this element.
     * It must be unique among the elements of its block.
     *
     * <p>Slack allows at most 255 characters.
     *
     * @param value value for Slack's {@code action_id} field
     * @return this builder
     */
    public Builder actionId(String value) {
      state.set("action_id", value);
      return this;
    }

    /**
     * Sets a confirmation dialog shown before the action is sent.
     *
     * @param value nested {@link Confirmation}
     * @return this builder
     */
    public Builder confirm(Confirmation value) {
      state.set("confirm", value);
      return this;
    }

    /**
     * Sets the button's emphasis. Omit it for the default neutral style.
     *
     * @param value value for Slack's {@code style} field
     * @return this builder
     */
    public Builder style(ButtonStyle value) {
      state.set("style", Objects.requireNonNull(value, "style").wireValue());
      return this;
    }

    /**
     * Sets the label read by screen readers in place of the visible text.
     *
     * @param value value for Slack's {@code accessibility_label} field
     * @return this builder
     */
    public Builder accessibilityLabel(String value) {
      state.set("accessibility_label", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link WorkflowButtonElement}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public WorkflowButtonElement build() {
      return state.build(WorkflowButtonElement::new);
    }
  }
}
