// Generated by java/generator/generate_models.py from spec/model.json.
package io.github.nicklambourne.slackblocks.internal;

/** Slack limits from spec/limits.json, one constant per dotted path. */
public final class SlackLimits {
  /** {@code action_id.max_length} */
  public static final int ACTION_ID_MAX_LENGTH = 255;

  /** {@code actions.elements.max_items} */
  public static final int ACTIONS_ELEMENTS_MAX_ITEMS = 25;

  /** {@code alert.text.max_length} */
  public static final int ALERT_TEXT_MAX_LENGTH = 200;

  /** {@code block_id.max_length} */
  public static final int BLOCK_ID_MAX_LENGTH = 255;

  /** {@code button.accessibility_label.max_length} */
  public static final int BUTTON_ACCESSIBILITY_LABEL_MAX_LENGTH = 75;

  /** {@code button.text.max_length} */
  public static final int BUTTON_TEXT_MAX_LENGTH = 75;

  /** {@code button.url.max_length} */
  public static final int BUTTON_URL_MAX_LENGTH = 3000;

  /** {@code button.value.max_length} */
  public static final int BUTTON_VALUE_MAX_LENGTH = 2000;

  /** {@code card.actions.max_items} */
  public static final int CARD_ACTIONS_MAX_ITEMS = 3;

  /** {@code card.body.max_length} */
  public static final int CARD_BODY_MAX_LENGTH = 200;

  /** {@code card.subtext.max_length} */
  public static final int CARD_SUBTEXT_MAX_LENGTH = 200;

  /** {@code card.subtitle.max_length} */
  public static final int CARD_SUBTITLE_MAX_LENGTH = 150;

  /** {@code card.title.max_length} */
  public static final int CARD_TITLE_MAX_LENGTH = 150;

  /** {@code carousel.elements.max_items} */
  public static final int CAROUSEL_ELEMENTS_MAX_ITEMS = 10;

  /** {@code carousel.elements.min_items} */
  public static final int CAROUSEL_ELEMENTS_MIN_ITEMS = 1;

  /** {@code checkboxes.options.max_items} */
  public static final int CHECKBOXES_OPTIONS_MAX_ITEMS = 10;

  /** {@code checkboxes.options.min_items} */
  public static final int CHECKBOXES_OPTIONS_MIN_ITEMS = 1;

  /** {@code confirmation.confirm.max_length} */
  public static final int CONFIRMATION_CONFIRM_MAX_LENGTH = 30;

  /** {@code confirmation.deny.max_length} */
  public static final int CONFIRMATION_DENY_MAX_LENGTH = 30;

  /** {@code confirmation.text.max_length} */
  public static final int CONFIRMATION_TEXT_MAX_LENGTH = 300;

  /** {@code confirmation.title.max_length} */
  public static final int CONFIRMATION_TITLE_MAX_LENGTH = 100;

  /** {@code container.child_blocks.max_items} */
  public static final int CONTAINER_CHILD_BLOCKS_MAX_ITEMS = 10;

  /** {@code container.subtitle.max_length} */
  public static final int CONTAINER_SUBTITLE_MAX_LENGTH = 150;

  /** {@code container.title.max_length} */
  public static final int CONTAINER_TITLE_MAX_LENGTH = 150;

  /** {@code context.elements.max_items} */
  public static final int CONTEXT_ELEMENTS_MAX_ITEMS = 10;

  /** {@code context_actions.elements.max_items} */
  public static final int CONTEXT_ACTIONS_ELEMENTS_MAX_ITEMS = 5;

  /** {@code data_table.cell_text.min_length} */
  public static final int DATA_TABLE_CELL_TEXT_MIN_LENGTH = 1;

  /** {@code data_table.columns.max_items} */
  public static final int DATA_TABLE_COLUMNS_MAX_ITEMS = 20;

  /** {@code data_table.columns.min_items} */
  public static final int DATA_TABLE_COLUMNS_MIN_ITEMS = 1;

  /** {@code data_table.content.max_length} */
  public static final int DATA_TABLE_CONTENT_MAX_LENGTH = 20000;

  /** {@code data_table.page_size.max} */
  public static final int DATA_TABLE_PAGE_SIZE_MAX = 100;

  /** {@code data_table.page_size.min} */
  public static final int DATA_TABLE_PAGE_SIZE_MIN = 1;

  /** {@code data_table.rows.max_items} */
  public static final int DATA_TABLE_ROWS_MAX_ITEMS = 201;

  /** {@code data_table.rows.min_items} */
  public static final int DATA_TABLE_ROWS_MIN_ITEMS = 2;

  /** {@code data_visualization.axis_label.max_length} */
  public static final int DATA_VISUALIZATION_AXIS_LABEL_MAX_LENGTH = 50;

  /** {@code data_visualization.categories.max_items} */
  public static final int DATA_VISUALIZATION_CATEGORIES_MAX_ITEMS = 20;

  /** {@code data_visualization.categories.min_items} */
  public static final int DATA_VISUALIZATION_CATEGORIES_MIN_ITEMS = 1;

  /** {@code data_visualization.category_label.max_length} */
  public static final int DATA_VISUALIZATION_CATEGORY_LABEL_MAX_LENGTH = 20;

  /** {@code data_visualization.data.max_items} */
  public static final int DATA_VISUALIZATION_DATA_MAX_ITEMS = 20;

  /** {@code data_visualization.data.min_items} */
  public static final int DATA_VISUALIZATION_DATA_MIN_ITEMS = 1;

  /** {@code data_visualization.point_label.max_length} */
  public static final int DATA_VISUALIZATION_POINT_LABEL_MAX_LENGTH = 20;

  /** {@code data_visualization.segment.label.max_length} */
  public static final int DATA_VISUALIZATION_SEGMENT_LABEL_MAX_LENGTH = 20;

  /** {@code data_visualization.segment.value.exclusive_min} */
  public static final int DATA_VISUALIZATION_SEGMENT_VALUE_EXCLUSIVE_MIN = 0;

  /** {@code data_visualization.segments.max_items} */
  public static final int DATA_VISUALIZATION_SEGMENTS_MAX_ITEMS = 12;

  /** {@code data_visualization.segments.min_items} */
  public static final int DATA_VISUALIZATION_SEGMENTS_MIN_ITEMS = 1;

  /** {@code data_visualization.series.max_items} */
  public static final int DATA_VISUALIZATION_SERIES_MAX_ITEMS = 12;

  /** {@code data_visualization.series.min_items} */
  public static final int DATA_VISUALIZATION_SERIES_MIN_ITEMS = 1;

  /** {@code data_visualization.series_name.max_length} */
  public static final int DATA_VISUALIZATION_SERIES_NAME_MAX_LENGTH = 20;

  /** {@code data_visualization.title.max_length} */
  public static final int DATA_VISUALIZATION_TITLE_MAX_LENGTH = 50;

  /** {@code date_picker.placeholder.max_length} */
  public static final int DATE_PICKER_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code dispatch_action_configuration.trigger_actions_on.max_items} */
  public static final int DISPATCH_ACTION_CONFIGURATION_TRIGGER_ACTIONS_ON_MAX_ITEMS = 2;

  /** {@code dispatch_action_configuration.trigger_actions_on.min_items} */
  public static final int DISPATCH_ACTION_CONFIGURATION_TRIGGER_ACTIONS_ON_MIN_ITEMS = 1;

  /** {@code email_input.placeholder.max_length} */
  public static final int EMAIL_INPUT_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code feedback_button.accessibility_label.max_length} */
  public static final int FEEDBACK_BUTTON_ACCESSIBILITY_LABEL_MAX_LENGTH = 75;

  /** {@code feedback_button.text.max_length} */
  public static final int FEEDBACK_BUTTON_TEXT_MAX_LENGTH = 75;

  /** {@code feedback_button.value.max_length} */
  public static final int FEEDBACK_BUTTON_VALUE_MAX_LENGTH = 2000;

  /** {@code file_input.max_files.max} */
  public static final int FILE_INPUT_MAX_FILES_MAX = 10;

  /** {@code file_input.max_files.min} */
  public static final int FILE_INPUT_MAX_FILES_MIN = 1;

  /** {@code header.text.max_length} */
  public static final int HEADER_TEXT_MAX_LENGTH = 150;

  /** {@code icon_button.accessibility_label.max_length} */
  public static final int ICON_BUTTON_ACCESSIBILITY_LABEL_MAX_LENGTH = 75;

  /** {@code icon_button.value.max_length} */
  public static final int ICON_BUTTON_VALUE_MAX_LENGTH = 2000;

  /** {@code icon_button.visible_to_user_ids.max_items} */
  public static final int ICON_BUTTON_VISIBLE_TO_USER_IDS_MAX_ITEMS = 10;

  /** {@code image.alt_text.max_length} */
  public static final int IMAGE_ALT_TEXT_MAX_LENGTH = 2000;

  /** {@code image.image_url.max_length} */
  public static final int IMAGE_IMAGE_URL_MAX_LENGTH = 3000;

  /** {@code input.hint.max_length} */
  public static final int INPUT_HINT_MAX_LENGTH = 2000;

  /** {@code input.label.max_length} */
  public static final int INPUT_LABEL_MAX_LENGTH = 2000;

  /** {@code markdown.text.max_length} */
  public static final int MARKDOWN_TEXT_MAX_LENGTH = 12000;

  /** {@code markdown.text.min_length} */
  public static final int MARKDOWN_TEXT_MIN_LENGTH = 1;

  /** {@code message.attachments.max_items} */
  public static final int MESSAGE_ATTACHMENTS_MAX_ITEMS = 100;

  /** {@code message.blocks.max_items} */
  public static final int MESSAGE_BLOCKS_MAX_ITEMS = 50;

  /** {@code message.channel.min_length} */
  public static final int MESSAGE_CHANNEL_MIN_LENGTH = 1;

  /** {@code number_input.placeholder.max_length} */
  public static final int NUMBER_INPUT_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code option.description.max_length} */
  public static final int OPTION_DESCRIPTION_MAX_LENGTH = 75;

  /** {@code option.text.max_length} */
  public static final int OPTION_TEXT_MAX_LENGTH = 75;

  /** {@code option.url.max_length} */
  public static final int OPTION_URL_MAX_LENGTH = 3000;

  /** {@code option.value.max_length} */
  public static final int OPTION_VALUE_MAX_LENGTH = 150;

  /** {@code option_group.label.max_length} */
  public static final int OPTION_GROUP_LABEL_MAX_LENGTH = 75;

  /** {@code option_group.options.max_items} */
  public static final int OPTION_GROUP_OPTIONS_MAX_ITEMS = 100;

  /** {@code option_group.options.min_items} */
  public static final int OPTION_GROUP_OPTIONS_MIN_ITEMS = 1;

  /** {@code overflow.options.max_items} */
  public static final int OVERFLOW_OPTIONS_MAX_ITEMS = 5;

  /** {@code overflow.options.min_items} */
  public static final int OVERFLOW_OPTIONS_MIN_ITEMS = 1;

  /** {@code plain_text_input.max_length.max} */
  public static final int PLAIN_TEXT_INPUT_MAX_LENGTH_MAX = 3000;

  /** {@code plain_text_input.placeholder.max_length} */
  public static final int PLAIN_TEXT_INPUT_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code radio_buttons.options.max_items} */
  public static final int RADIO_BUTTONS_OPTIONS_MAX_ITEMS = 10;

  /** {@code radio_buttons.options.min_items} */
  public static final int RADIO_BUTTONS_OPTIONS_MIN_ITEMS = 1;

  /** {@code rich_text_input.placeholder.max_length} */
  public static final int RICH_TEXT_INPUT_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code section.fields.item_max_length} */
  public static final int SECTION_FIELDS_ITEM_MAX_LENGTH = 2000;

  /** {@code section.fields.max_items} */
  public static final int SECTION_FIELDS_MAX_ITEMS = 10;

  /** {@code section.text.max_length} */
  public static final int SECTION_TEXT_MAX_LENGTH = 3000;

  /** {@code select.option_groups.max_items} */
  public static final int SELECT_OPTION_GROUPS_MAX_ITEMS = 100;

  /** {@code select.options.max_items} */
  public static final int SELECT_OPTIONS_MAX_ITEMS = 100;

  /** {@code select.placeholder.max_length} */
  public static final int SELECT_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code table.columns.max_items} */
  public static final int TABLE_COLUMNS_MAX_ITEMS = 20;

  /** {@code table.rows.max_items} */
  public static final int TABLE_ROWS_MAX_ITEMS = 100;

  /** {@code text.max_length} */
  public static final int TEXT_MAX_LENGTH = 3000;

  /** {@code text.min_length} */
  public static final int TEXT_MIN_LENGTH = 1;

  /** {@code time_picker.placeholder.max_length} */
  public static final int TIME_PICKER_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code url_input.placeholder.max_length} */
  public static final int URL_INPUT_PLACEHOLDER_MAX_LENGTH = 150;

  /** {@code url_source.url.max_length} */
  public static final int URL_SOURCE_URL_MAX_LENGTH = 3000;

  /** {@code url_source.url.min_length} */
  public static final int URL_SOURCE_URL_MIN_LENGTH = 1;

  /** {@code video.alt_text.max_length} */
  public static final int VIDEO_ALT_TEXT_MAX_LENGTH = 2000;

  /** {@code video.author_name.max_length} */
  public static final int VIDEO_AUTHOR_NAME_MAX_LENGTH = 50;

  /** {@code video.description.max_length} */
  public static final int VIDEO_DESCRIPTION_MAX_LENGTH = 200;

  /** {@code video.provider_name.max_length} */
  public static final int VIDEO_PROVIDER_NAME_MAX_LENGTH = 50;

  /** {@code video.title.max_length} */
  public static final int VIDEO_TITLE_MAX_LENGTH = 200;

  /** {@code view.blocks.max_items} */
  public static final int VIEW_BLOCKS_MAX_ITEMS = 100;

  /** {@code view.blocks.min_items} */
  public static final int VIEW_BLOCKS_MIN_ITEMS = 1;

  /** {@code view.callback_id.max_length} */
  public static final int VIEW_CALLBACK_ID_MAX_LENGTH = 255;

  /** {@code view.close.max_length} */
  public static final int VIEW_CLOSE_MAX_LENGTH = 24;

  /** {@code view.private_metadata.max_length} */
  public static final int VIEW_PRIVATE_METADATA_MAX_LENGTH = 3000;

  /** {@code view.submit.max_length} */
  public static final int VIEW_SUBMIT_MAX_LENGTH = 24;

  /** {@code view.title.max_length} */
  public static final int VIEW_TITLE_MAX_LENGTH = 24;

  /** {@code workflow_button.accessibility_label.max_length} */
  public static final int WORKFLOW_BUTTON_ACCESSIBILITY_LABEL_MAX_LENGTH = 75;

  /** {@code workflow_button.text.max_length} */
  public static final int WORKFLOW_BUTTON_TEXT_MAX_LENGTH = 75;

  private SlackLimits() {}
}
