package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// The published module contains only go/, so validation cannot read spec/limits.json at run time.
// Instead every scalar leaf becomes an unexported constant in this checked-in file.
const limitsGeneratedFile = "limits_gen.go"

// limitInitialisms keeps the generated constant names consistent with Go naming conventions.
var limitInitialisms = map[string]string{"id": "ID", "ids": "IDs", "url": "URL"}

func writeLimits(root string) {
	data, err := os.ReadFile(filepath.Join(root, "..", limitsFile))
	must(err)
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var limits map[string]any
	must(decoder.Decode(&limits))

	leaves := map[string]json.Number{}
	flattenLimits("", limits, leaves)
	paths := make([]string, 0, len(leaves))
	for path := range leaves {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("package slackblocks\n\n")
	output.WriteString("// Slack limits from spec/limits.json, one constant per dotted path.\n")
	output.WriteString("const (\n")
	names := map[string]string{}
	for _, path := range paths {
		name := limitConstant(path)
		if previous, ok := names[name]; ok {
			panic(fmt.Sprintf("limits paths %s and %s both map to %s", previous, path, name))
		}
		names[name] = path
		if _, err := leaves[path].Int64(); err != nil {
			panic(fmt.Sprintf("limits path %s is not an integer", path))
		}
		fmt.Fprintf(&output, "\t%s = %s // %s\n", name, leaves[path], path)
	}
	output.WriteString(")\n")

	formatted, err := format.Source(output.Bytes())
	must(err)
	must(os.WriteFile(filepath.Join(root, limitsGeneratedFile), formatted, 0o644))
}

func flattenLimits(prefix string, node map[string]any, leaves map[string]json.Number) {
	for key, value := range node {
		path := key
		if prefix != "" {
			path = prefix + "." + key
		}
		switch typed := value.(type) {
		case map[string]any:
			flattenLimits(path, typed, leaves)
		case json.Number:
			leaves[path] = typed
		default:
			panic(fmt.Sprintf("limits path %s is neither an object nor a number", path))
		}
	}
}

// limitConstant names the constant for a dotted limits path, e.g. button.url.max_length becomes
// limitButtonURLMaxLength.
func limitConstant(path string) string {
	var name strings.Builder
	name.WriteString("limit")
	for _, part := range strings.FieldsFunc(path, func(r rune) bool { return r == '.' || r == '_' }) {
		if initialism, ok := limitInitialisms[part]; ok {
			name.WriteString(initialism)
		} else {
			name.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	return name.String()
}
