<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** Severity levels supported by alert blocks. */
enum AlertLevel: string
{
    /** Neutral styling. */
    case Default = 'default';
    /** Informational styling. */
    case Info = 'info';
    /** Warning styling. */
    case Warning = 'warning';
    /** Error styling. */
    case Error = 'error';
    /** Success styling. */
    case Success = 'success';
}
