<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A severity-labelled alert, available in modals.
 * @see https://docs.slack.dev/reference/block-kit/blocks/alert-block
 */
final readonly class AlertBlock extends Value implements Block
{
    /** Sets the alert message.
     * @var Text
     */
    public Text $text;

    /** Sets the alert severity, which controls its color and icon.
     * @var AlertLevel|null
     */
    public AlertLevel|null $level;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param Text|string $text Sets the alert message.
     * @param AlertLevel|null $level Sets the alert severity, which controls its color and icon.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        Text|string $text,
        AlertLevel|null $level = null,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->text = is_string($text) ? new MarkdownText($text) : $text;
        $this->level = $level;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
