<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A legacy message attachment containing blocks and an optional color bar.
 * @see https://docs.slack.dev/messaging/formatting-message-text#when-to-use-attachments
 * Only blocks supported in messages are accepted.
 */
final readonly class Attachment extends Value
{
    /** Adds the attachment's blocks in display order.
     * @var list<Block>
     */
    public array $blocks;

    /** Sets the attachment's left border color: a six-digit hex color or good, warning, or danger.
     * @var string|null
     */
    public string|null $color;

    /** Sets plain-text summary shown in clients that cannot display attachments.
     * @var string|null
     */
    public string|null $fallback;

    /**
     * @param list<Block> $blocks Adds the attachment's blocks in display order.
     * @param string|null $color Sets the attachment's left border color: a six-digit hex color or good, warning, or danger.
     * @param string|null $fallback Sets plain-text summary shown in clients that cannot display attachments.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $blocks,
        string|null $color = null,
        string|null $fallback = null,
        ?JsonObject $extensions = null,
    ) {
        $this->blocks = $blocks;
        $this->color = $color !== null && preg_match('/\A[0-9a-fA-F]{6}\z/', $color) === 1 ? '#' . $color : $color;
        $this->fallback = $fallback;
        parent::__construct($extensions);
    }
}
