<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * An interactive button that sends a payload or opens a URL.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/button-element
 */
final readonly class ButtonElement extends Value implements Element
{
    /** Sets the button label.
     * @var PlainText
     */
    public PlainText $text;

    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Sets a URL opened in the user's browser when the button is clicked. Slack still sends an interaction payload.
     * @var string|null
     */
    public string|null $url;

    /** Sets the application-defined value sent in interaction payloads.
     * @var string|null
     */
    public string|null $value;

    /** Sets the button's emphasis. Omit it for the default neutral style.
     * @var ButtonStyle|null
     */
    public ButtonStyle|null $style;

    /** Sets a confirmation dialog shown before the action is sent.
     * @var Confirmation|null
     */
    public Confirmation|null $confirm;

    /** Sets the label read by screen readers in place of the visible text.
     * @var string|null
     */
    public string|null $accessibilityLabel;

    /**
     * @param PlainText|string $text Sets the button label.
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param string|null $url Sets a URL opened in the user's browser when the button is clicked. Slack still sends an interaction payload.
     * @param string|null $value Sets the application-defined value sent in interaction payloads.
     * @param ButtonStyle|null $style Sets the button's emphasis. Omit it for the default neutral style.
     * @param Confirmation|null $confirm Sets a confirmation dialog shown before the action is sent.
     * @param string|null $accessibilityLabel Sets the label read by screen readers in place of the visible text.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        PlainText|string $text,
        string|null $actionId = null,
        string|null $url = null,
        string|null $value = null,
        ButtonStyle|null $style = null,
        Confirmation|null $confirm = null,
        string|null $accessibilityLabel = null,
        ?JsonObject $extensions = null,
    ) {
        $this->text = is_string($text) ? new PlainText($text) : $text;
        $this->actionId = $actionId;
        $this->url = $url;
        $this->value = $value;
        $this->style = $style;
        $this->confirm = $confirm;
        $this->accessibilityLabel = $accessibilityLabel;
        parent::__construct($extensions);
    }
}
