<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A compact card with an image, text, and up to three buttons.
 * @see https://docs.slack.dev/reference/block-kit/blocks/card-block
 * Provide at least one of a hero image, title, actions, or body.
 * An image icon and a Slack icon cannot be combined.
 */
final readonly class CardBlock extends Value implements Block
{
    /** Sets the image displayed prominently at the top of the card.
     * @var ImageElement|null
     */
    public ImageElement|null $heroImage;

    /** Sets the image displayed beside the title.
     * @var ImageElement|null
     */
    public ImageElement|null $icon;

    /** Sets the card title.
     * @var Text|null
     */
    public Text|null $title;

    /** Sets the supporting text shown below the title.
     * @var Text|null
     */
    public Text|null $subtitle;

    /** Sets the main body text of the card.
     * @var Text|null
     */
    public Text|null $body;

    /** Adds buttons displayed at the bottom of the card, in display order.
     * @var list<ButtonElement>|null
     */
    public array|null $actions;

    /** Sets a Slack-provided icon displayed beside the title. Cannot be combined with an image icon.
     * @var SlackIcon|null
     */
    public SlackIcon|null $slackIcon;

    /** Sets the small print shown at the bottom of the card.
     * @var Text|null
     */
    public Text|null $subtext;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param ImageElement|null $heroImage Sets the image displayed prominently at the top of the card.
     * @param ImageElement|null $icon Sets the image displayed beside the title.
     * @param Text|string|null $title Sets the card title.
     * @param Text|string|null $subtitle Sets the supporting text shown below the title.
     * @param Text|string|null $body Sets the main body text of the card.
     * @param list<ButtonElement>|null $actions Adds buttons displayed at the bottom of the card, in display order.
     * @param SlackIcon|null $slackIcon Sets a Slack-provided icon displayed beside the title. Cannot be combined with an image icon.
     * @param Text|string|null $subtext Sets the small print shown at the bottom of the card.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        ImageElement|null $heroImage = null,
        ImageElement|null $icon = null,
        Text|string|null $title = null,
        Text|string|null $subtitle = null,
        Text|string|null $body = null,
        array|null $actions = null,
        SlackIcon|null $slackIcon = null,
        Text|string|null $subtext = null,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->heroImage = $heroImage;
        $this->icon = $icon;
        $this->title = is_string($title) ? new MarkdownText($title) : $title;
        $this->subtitle = is_string($subtitle) ? new MarkdownText($subtitle) : $subtitle;
        $this->body = is_string($body) ? new MarkdownText($body) : $body;
        $this->actions = $actions;
        $this->slackIcon = $slackIcon;
        $this->subtext = is_string($subtext) ? new MarkdownText($subtext) : $subtext;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
