<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** A chart that can be displayed by a data visualization block. */
interface Chart extends \JsonSerializable {}
