<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A group of checkboxes.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/checkboxes-element
 */
final readonly class CheckboxesElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Adds selectable options in display order.
     * @var list<Option>
     */
    public array $options;

    /** Adds options that are selected when the element loads. Each must match an option in the element.
     * @var list<Option>|null
     */
    public array|null $initialOptions;

    /** Sets a confirmation dialog shown before the action is sent.
     * @var Confirmation|null
     */
    public Confirmation|null $confirm;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /**
     * @param list<Option> $options Adds selectable options in display order.
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param list<Option>|null $initialOptions Adds options that are selected when the element loads. Each must match an option in the element.
     * @param Confirmation|null $confirm Sets a confirmation dialog shown before the action is sent.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $options,
        string|null $actionId = null,
        array|null $initialOptions = null,
        Confirmation|null $confirm = null,
        bool|null $focusOnLoad = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->options = $options;
        $this->initialOptions = $initialOptions;
        $this->confirm = $confirm;
        $this->focusOnLoad = $focusOnLoad;
        parent::__construct($extensions);
    }
}
