<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A dialog that asks users to confirm an action before it is sent.
 * @see https://docs.slack.dev/reference/block-kit/composition-objects/confirmation-dialog-object
 */
final readonly class Confirmation extends Value
{
    /** Sets the dialog title.
     * @var PlainText
     */
    public PlainText $title;

    /** Sets the explanatory text in the dialog body.
     * @var Text
     */
    public Text $text;

    /** Sets the label of the button that confirms the action.
     * @var PlainText
     */
    public PlainText $confirm;

    /** Sets the label of the button that cancels the action.
     * @var PlainText
     */
    public PlainText $deny;

    /** Sets the emphasis of the confirm button.
     * @var ButtonStyle|null
     */
    public ButtonStyle|null $style;

    /**
     * @param PlainText|string $title Sets the dialog title.
     * @param Text|string $text Sets the explanatory text in the dialog body.
     * @param PlainText|string $confirm Sets the label of the button that confirms the action.
     * @param PlainText|string $deny Sets the label of the button that cancels the action.
     * @param ButtonStyle|null $style Sets the emphasis of the confirm button.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        PlainText|string $title,
        Text|string $text,
        PlainText|string $confirm,
        PlainText|string $deny,
        ButtonStyle|null $style = null,
        ?JsonObject $extensions = null,
    ) {
        $this->title = is_string($title) ? new PlainText($title) : $title;
        $this->text = is_string($text) ? new MarkdownText($text) : $text;
        $this->confirm = is_string($confirm) ? new PlainText($confirm) : $confirm;
        $this->deny = is_string($deny) ? new PlainText($deny) : $deny;
        $this->style = $style;
        parent::__construct($extensions);
    }
}
