<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** A value that can appear in a context actions block: feedback buttons or an icon button. */
interface ContextActionsElement extends \JsonSerializable
{
    /** @return array<string, mixed> Slack wire fields. */
    public function toArray(): array;

    /** Encodes this validated value as Slack JSON. */
    public function toJson(): string;
}
