<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A titled group of blocks that can optionally collapse.
 * @see https://docs.slack.dev/reference/block-kit/blocks/container-block
 * Provide a title or a rich text title.
 */
final readonly class ContainerBlock extends Value implements Block
{
    /** Adds the blocks grouped inside the container, in display order.
     * @var list<Block>
     */
    public array $childBlocks;

    /** Sets the container title. Provide either a title or a rich text title.
     * @var PlainText|null
     */
    public PlainText|null $title;

    /** Sets a rich text block used as the title in place of a plain-text title.
     * @var RichTextBlock|null
     */
    public RichTextBlock|null $richTextTitle;

    /** Sets the supporting text shown below the title.
     * @var Text|null
     */
    public Text|null $subtitle;

    /** Sets the horizontal width of the container.
     * @var ContainerWidth|null
     */
    public ContainerWidth|null $width;

    /** Sets the image displayed beside the title.
     * @var ImageElement|null
     */
    public ImageElement|null $icon;

    /** Sets whether users can collapse and expand the container.
     * @var bool|null
     */
    public bool|null $isCollapsible;

    /** Sets whether a collapsible container starts collapsed. Requires the container to be collapsible.
     * @var bool|null
     */
    public bool|null $defaultCollapsed;

    /** Sets whether Slack draws a divider below the container header. Only valid for non-collapsible containers.
     * @var bool|null
     */
    public bool|null $hasHeaderDivider;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param list<Block> $childBlocks Adds the blocks grouped inside the container, in display order.
     * @param PlainText|string|null $title Sets the container title. Provide either a title or a rich text title.
     * @param RichTextBlock|null $richTextTitle Sets a rich text block used as the title in place of a plain-text title.
     * @param Text|string|null $subtitle Sets the supporting text shown below the title.
     * @param ContainerWidth|null $width Sets the horizontal width of the container.
     * @param ImageElement|null $icon Sets the image displayed beside the title.
     * @param bool|null $isCollapsible Sets whether users can collapse and expand the container.
     * @param bool|null $defaultCollapsed Sets whether a collapsible container starts collapsed. Requires the container to be collapsible.
     * @param bool|null $hasHeaderDivider Sets whether Slack draws a divider below the container header. Only valid for non-collapsible containers.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $childBlocks,
        PlainText|string|null $title = null,
        RichTextBlock|null $richTextTitle = null,
        Text|string|null $subtitle = null,
        ContainerWidth|null $width = null,
        ImageElement|null $icon = null,
        bool|null $isCollapsible = null,
        bool|null $defaultCollapsed = null,
        bool|null $hasHeaderDivider = null,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->childBlocks = $childBlocks;
        $this->title = is_string($title) ? new PlainText($title) : $title;
        $this->richTextTitle = $richTextTitle;
        $this->subtitle = is_string($subtitle) ? new MarkdownText($subtitle) : $subtitle;
        $this->width = $width;
        $this->icon = $icon;
        $this->isCollapsible = $isCollapsible;
        $this->defaultCollapsed = $defaultCollapsed;
        $this->hasHeaderDivider = $hasHeaderDivider;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
