<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A block of small, secondary images and text.
 * @see https://docs.slack.dev/reference/block-kit/blocks/context-block
 */
final readonly class ContextBlock extends Value implements Block
{
    /** Adds images and text in display order.
     * @var list<ContextElement>
     */
    public array $elements;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param list<ContextElement> $elements Adds images and text in display order.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $elements,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->elements = $elements;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
