<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * Limits which conversations a conversation menu offers.
 * @see https://docs.slack.dev/reference/block-kit/composition-objects/conversation-filter-object
 * Set at least one filter.
 * Include only im, mpim, private, and public.
 */
final readonly class ConversationFilter extends Value
{
    /** Adds conversation types to offer: im, mpim, private, or public.
     * @var list<string>|null
     */
    public array|null $include;

    /** Sets whether externally shared channels are excluded.
     * @var bool|null
     */
    public bool|null $excludeExternalSharedChannels;

    /** Sets whether bot users are excluded.
     * @var bool|null
     */
    public bool|null $excludeBotUsers;

    /**
     * @param list<string>|null $include Adds conversation types to offer: im, mpim, private, or public.
     * @param bool|null $excludeExternalSharedChannels Sets whether externally shared channels are excluded.
     * @param bool|null $excludeBotUsers Sets whether bot users are excluded.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array|null $include = null,
        bool|null $excludeExternalSharedChannels = null,
        bool|null $excludeBotUsers = null,
        ?JsonObject $extensions = null,
    ) {
        $this->include = $include;
        $this->excludeExternalSharedChannels = $excludeExternalSharedChannels;
        $this->excludeBotUsers = $excludeBotUsers;
        parent::__construct($extensions);
    }
}
