<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A named series of chart data points.
 * @see https://docs.slack.dev/reference/block-kit/blocks/data-visualization-block
 */
final readonly class DataSeries extends Value
{
    /** Sets the series name shown in the legend.
     * @var string
     */
    public string $name;

    /** Adds data points in axis-category order.
     * @var list<DataPoint>
     */
    public array $data;

    /**
     * @param string $name Sets the series name shown in the legend.
     * @param list<DataPoint> $data Adds data points in axis-category order.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $name,
        array $data,
        ?JsonObject $extensions = null,
    ) {
        $this->name = $name;
        $this->data = $data;
        parent::__construct($extensions);
    }
}
