<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A single-line input that accepts an email address.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/email-input-element
 */
final readonly class EmailInputElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Sets the value present when the input loads.
     * @var string|null
     */
    public string|null $initialValue;

    /** Sets which user interactions send a block_actions payload.
     * @var DispatchActionConfiguration|null
     */
    public DispatchActionConfiguration|null $dispatchActionConfig;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /** Sets the placeholder text shown before a value is chosen.
     * @var PlainText|null
     */
    public PlainText|null $placeholder;

    /**
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param string|null $initialValue Sets the value present when the input loads.
     * @param DispatchActionConfiguration|null $dispatchActionConfig Sets which user interactions send a block_actions payload.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param PlainText|string|null $placeholder Sets the placeholder text shown before a value is chosen.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string|null $actionId = null,
        string|null $initialValue = null,
        DispatchActionConfiguration|null $dispatchActionConfig = null,
        bool|null $focusOnLoad = null,
        PlainText|string|null $placeholder = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->initialValue = $initialValue;
        $this->dispatchActionConfig = $dispatchActionConfig;
        $this->focusOnLoad = $focusOnLoad;
        $this->placeholder = is_string($placeholder) ? new PlainText($placeholder) : $placeholder;
        parent::__construct($extensions);
    }
}
