<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A menu for selecting multiple options loaded from your app.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/multi-select-menu-element
 */
final readonly class ExternalMultiSelectElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Sets how many characters the user must type before Slack queries your options endpoint.
     * @var int|null
     */
    public int|null $minQueryLength;

    /** Adds options that are selected when the element loads. Each must match an option in the element.
     * @var list<Option>|null
     */
    public array|null $initialOptions;

    /** Sets a confirmation dialog shown before the action is sent.
     * @var Confirmation|null
     */
    public Confirmation|null $confirm;

    /** Sets the maximum number of items a user can select.
     * @var int|null
     */
    public int|null $maxSelectedItems;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /** Sets the placeholder text shown before a value is chosen.
     * @var PlainText|null
     */
    public PlainText|null $placeholder;

    /**
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param int|null $minQueryLength Sets how many characters the user must type before Slack queries your options endpoint.
     * @param list<Option>|null $initialOptions Adds options that are selected when the element loads. Each must match an option in the element.
     * @param Confirmation|null $confirm Sets a confirmation dialog shown before the action is sent.
     * @param int|null $maxSelectedItems Sets the maximum number of items a user can select.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param PlainText|string|null $placeholder Sets the placeholder text shown before a value is chosen.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string|null $actionId = null,
        int|null $minQueryLength = null,
        array|null $initialOptions = null,
        Confirmation|null $confirm = null,
        int|null $maxSelectedItems = null,
        bool|null $focusOnLoad = null,
        PlainText|string|null $placeholder = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->minQueryLength = $minQueryLength;
        $this->initialOptions = $initialOptions;
        $this->confirm = $confirm;
        $this->maxSelectedItems = $maxSelectedItems;
        $this->focusOnLoad = $focusOnLoad;
        $this->placeholder = is_string($placeholder) ? new PlainText($placeholder) : $placeholder;
        parent::__construct($extensions);
    }
}
