<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * An input that lets users upload files.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/file-input-element
 */
final readonly class FileInputElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Adds accepted file extensions, such as pdf or png.
     * @var list<string>|null
     */
    public array|null $filetypes;

    /** Sets the maximum number of files a user can upload.
     * @var int|null
     */
    public int|null $maxFiles;

    /**
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param list<string>|null $filetypes Adds accepted file extensions, such as pdf or png.
     * @param int|null $maxFiles Sets the maximum number of files a user can upload.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string|null $actionId = null,
        array|null $filetypes = null,
        int|null $maxFiles = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->filetypes = $filetypes;
        $this->maxFiles = $maxFiles;
        parent::__construct($extensions);
    }
}
