<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * Large, bold plain text that introduces a group of blocks.
 * @see https://docs.slack.dev/reference/block-kit/blocks/header-block
 */
final readonly class HeaderBlock extends Value implements Block
{
    /** Sets the header text, shown in a larger bold font.
     * @var PlainText
     */
    public PlainText $text;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param PlainText|string $text Sets the header text, shown in a larger bold font.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        PlainText|string $text,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->text = is_string($text) ? new PlainText($text) : $text;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
