<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** Icons supported by icon buttons. */
enum IconButtonIcon: string
{
    /** A trash can, for delete actions. */
    case Trash = 'trash';
}
