<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * An image displayed inside a section, context, or card.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/image-element
 * Provide exactly one of an image URL or a Slack file.
 */
final readonly class ImageElement extends Value implements Element, ContextElement
{
    /** Sets a plain-text summary of the image or video for assistive technology.
     * @var string
     */
    public string $altText;

    /** Sets the publicly accessible URL of the image. Cannot be combined with a Slack file.
     * @var string|null
     */
    public string|null $imageUrl;

    /** Sets a file hosted in Slack as the image source. Cannot be combined with an image URL.
     * @var SlackFile|null
     */
    public SlackFile|null $slackFile;

    /**
     * @param string $altText Sets a plain-text summary of the image or video for assistive technology.
     * @param string|null $imageUrl Sets the publicly accessible URL of the image. Cannot be combined with a Slack file.
     * @param SlackFile|null $slackFile Sets a file hosted in Slack as the image source. Cannot be combined with an image URL.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $altText,
        string|null $imageUrl = null,
        SlackFile|null $slackFile = null,
        ?JsonObject $extensions = null,
    ) {
        $this->altText = $altText;
        $this->imageUrl = $imageUrl;
        $this->slackFile = $slackFile;
        parent::__construct($extensions);
    }
}
