<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A standalone image with alternative text and an optional title.
 * @see https://docs.slack.dev/reference/block-kit/blocks/image-block
 * Provide exactly one of an image URL or a Slack file.
 */
final readonly class ImageBlock extends Value implements Block
{
    /** Sets the publicly accessible URL of the image. Cannot be combined with a Slack file.
     * @var string|null
     */
    public string|null $imageUrl;

    /** Sets a file hosted in Slack as the image source. Cannot be combined with an image URL.
     * @var SlackFile|null
     */
    public SlackFile|null $slackFile;

    /** Sets a plain-text summary of the image or video for assistive technology.
     * @var string
     */
    public string $altText;

    /** Sets the title shown above the image.
     * @var PlainText|null
     */
    public PlainText|null $title;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param string $altText Sets a plain-text summary of the image or video for assistive technology.
     * @param string|null $imageUrl Sets the publicly accessible URL of the image. Cannot be combined with a Slack file.
     * @param SlackFile|null $slackFile Sets a file hosted in Slack as the image source. Cannot be combined with an image URL.
     * @param PlainText|string|null $title Sets the title shown above the image.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $altText,
        string|null $imageUrl = null,
        SlackFile|null $slackFile = null,
        PlainText|string|null $title = null,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->imageUrl = $imageUrl;
        $this->slackFile = $slackFile;
        $this->altText = $altText;
        $this->title = is_string($title) ? new PlainText($title) : $title;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
