<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** An element that can be placed in an input block. */
interface InputElement extends Element {}
