<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A labelled input that collects a value in a modal, App Home, or message.
 * @see https://docs.slack.dev/reference/block-kit/blocks/input-block
 */
final readonly class InputBlock extends Value implements Block
{
    /** Sets the label shown above the input.
     * @var PlainText
     */
    public PlainText $label;

    /** Sets the input element that collects the user's value.
     * @var InputElement
     */
    public InputElement $element;

    /** Sets whether changing the element sends a block_actions payload immediately.
     * @var bool|null
     */
    public bool|null $dispatchAction;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /** Sets helper text shown below the input.
     * @var PlainText|null
     */
    public PlainText|null $hint;

    /** Sets whether the modal can be submitted when this input is empty.
     * @var bool|null
     */
    public bool|null $optional;

    /**
     * @param PlainText|string $label Sets the label shown above the input.
     * @param InputElement $element Sets the input element that collects the user's value.
     * @param bool|null $dispatchAction Sets whether changing the element sends a block_actions payload immediately.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param PlainText|string|null $hint Sets helper text shown below the input.
     * @param bool|null $optional Sets whether the modal can be submitted when this input is empty.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        PlainText|string $label,
        InputElement $element,
        bool|null $dispatchAction = null,
        string|null $blockId = null,
        PlainText|string|null $hint = null,
        bool|null $optional = null,
        ?JsonObject $extensions = null,
    ) {
        $this->label = is_string($label) ? new PlainText($label) : $label;
        $this->element = $element;
        $this->dispatchAction = $dispatchAction;
        $this->blockId = $blockId;
        $this->hint = is_string($hint) ? new PlainText($hint) : $hint;
        $this->optional = $optional;
        parent::__construct($extensions);
    }
}
