<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * Standard markdown rendered by Slack, intended for AI-generated content.
 * @see https://docs.slack.dev/reference/block-kit/blocks/markdown-block
 */
final readonly class MarkdownBlock extends Value implements Block
{
    /** Sets standard markdown content, which Slack renders directly.
     * @var string
     */
    public string $text;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param string $text Sets standard markdown content, which Slack renders directly.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $text,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->text = $text;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
