<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A response body for slash commands and interaction response URLs.
 * @see https://docs.slack.dev/interactivity/handling-user-interaction#message_responses
 * Only blocks supported in messages are accepted.
 * Markdown block text is limited to 12,000 characters, and data table cell text to 20,000 characters, across the whole message.
 */
final readonly class MessageResponse extends Value
{
    /** Adds the response blocks in display order.
     * @var list<Block>|null
     */
    public array|null $blocks;

    /** Adds legacy attachments in display order.
     * @var list<Attachment>|null
     */
    public array|null $attachments;

    /** Sets the fallback text used in notifications and by clients that cannot display blocks.
     * @var string|null
     */
    public string|null $text;

    /** Sets whether Slack formats the top-level text as mrkdwn.
     * @var bool|null
     */
    public bool|null $mrkdwn;

    /** Sets whether the response replaces the message that triggered it.
     * @var bool|null
     */
    public bool|null $replaceOriginal;

    /** Sets who can see the response.
     * @var ResponseType|null
     */
    public ResponseType|null $responseType;

    /**
     * @param list<Block>|null $blocks Adds the response blocks in display order.
     * @param list<Attachment>|null $attachments Adds legacy attachments in display order.
     * @param string|null $text Sets the fallback text used in notifications and by clients that cannot display blocks.
     * @param bool|null $mrkdwn Sets whether Slack formats the top-level text as mrkdwn.
     * @param bool|null $replaceOriginal Sets whether the response replaces the message that triggered it.
     * @param ResponseType|null $responseType Sets who can see the response.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array|null $blocks = null,
        array|null $attachments = null,
        string|null $text = '',
        bool|null $mrkdwn = true,
        bool|null $replaceOriginal = false,
        ResponseType|null $responseType = ResponseType::InChannel,
        ?JsonObject $extensions = null,
    ) {
        $this->blocks = $blocks;
        $this->attachments = $attachments;
        $this->text = $text;
        $this->mrkdwn = $mrkdwn;
        $this->replaceOriginal = $replaceOriginal;
        $this->responseType = $responseType;
        parent::__construct($extensions);
    }
}
