<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A complete payload for chat.postMessage and related Web API methods.
 * @see https://docs.slack.dev/reference/methods/chat.postMessage
 * Only blocks supported in messages are accepted.
 * Markdown block text is limited to 12,000 characters, and data table cell text to 20,000 characters, across the whole message.
 */
final readonly class MessagePayload extends Value
{
    /** Sets the ID of the channel, private group, or conversation that receives the message.
     * @var string
     */
    public string $channel;

    /** Adds the message blocks in display order.
     * @var list<Block>|null
     */
    public array|null $blocks;

    /** Adds legacy attachments in display order.
     * @var list<Attachment>|null
     */
    public array|null $attachments;

    /** Sets the fallback text used in notifications and by clients that cannot display blocks.
     * @var string|null
     */
    public string|null $text;

    /** Sets whether Slack formats the top-level text as mrkdwn.
     * @var bool|null
     */
    public bool|null $mrkdwn;

    /** Sets whether Slack unfurls text-based links.
     * @var bool|null
     */
    public bool|null $unfurlLinks;

    /** Sets whether Slack unfurls media links.
     * @var bool|null
     */
    public bool|null $unfurlMedia;

    /** Sets message metadata as a JSON-compatible map, such as event_type and event_payload.
     * @var JsonObject|null
     */
    public JsonObject|null $metadata;

    /**
     * @param string $channel Sets the ID of the channel, private group, or conversation that receives the message.
     * @param list<Block>|null $blocks Adds the message blocks in display order.
     * @param list<Attachment>|null $attachments Adds legacy attachments in display order.
     * @param string|null $text Sets the fallback text used in notifications and by clients that cannot display blocks.
     * @param bool|null $mrkdwn Sets whether Slack formats the top-level text as mrkdwn.
     * @param bool|null $unfurlLinks Sets whether Slack unfurls text-based links.
     * @param bool|null $unfurlMedia Sets whether Slack unfurls media links.
     * @param JsonObject|null $metadata Sets message metadata as a JSON-compatible map, such as event_type and event_payload.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $channel,
        array|null $blocks = null,
        array|null $attachments = null,
        string|null $text = '',
        bool|null $mrkdwn = true,
        bool|null $unfurlLinks = null,
        bool|null $unfurlMedia = null,
        JsonObject|null $metadata = null,
        ?JsonObject $extensions = null,
    ) {
        $this->channel = $channel;
        $this->blocks = $blocks;
        $this->attachments = $attachments;
        $this->text = $text;
        $this->mrkdwn = $mrkdwn;
        $this->unfurlLinks = $unfurlLinks;
        $this->unfurlMedia = $unfurlMedia;
        $this->metadata = $metadata;
        parent::__construct($extensions);
    }
}
