<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A labelled group of options in a static select menu.
 * @see https://docs.slack.dev/reference/block-kit/composition-objects/option-group-object
 */
final readonly class OptionGroup extends Value
{
    /** Sets the group heading.
     * @var PlainText
     */
    public PlainText $label;

    /** Adds selectable options in display order.
     * @var list<Option>
     */
    public array $options;

    /**
     * @param PlainText|string $label Sets the group heading.
     * @param list<Option> $options Adds selectable options in display order.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        PlainText|string $label,
        array $options,
        ?JsonObject $extensions = null,
    ) {
        $this->label = is_string($label) ? new PlainText($label) : $label;
        $this->options = $options;
        parent::__construct($extensions);
    }
}
