<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A single-line or multi-line free-text input.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/plain-text-input-element
 */
final readonly class PlainTextInputElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Sets the value present when the input loads.
     * @var string|null
     */
    public string|null $initialValue;

    /** Sets whether the input is a multi-line text area.
     * @var bool|null
     */
    public bool|null $multiline;

    /** Sets the minimum number of characters the user must enter.
     * @var int|null
     */
    public int|null $minLength;

    /** Sets the maximum number of characters the user can enter.
     * @var int|null
     */
    public int|null $maxLength;

    /** Sets which user interactions send a block_actions payload.
     * @var DispatchActionConfiguration|null
     */
    public DispatchActionConfiguration|null $dispatchActionConfig;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /** Sets the placeholder text shown before a value is chosen.
     * @var PlainText|null
     */
    public PlainText|null $placeholder;

    /**
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param string|null $initialValue Sets the value present when the input loads.
     * @param bool|null $multiline Sets whether the input is a multi-line text area.
     * @param int|null $minLength Sets the minimum number of characters the user must enter.
     * @param int|null $maxLength Sets the maximum number of characters the user can enter.
     * @param DispatchActionConfiguration|null $dispatchActionConfig Sets which user interactions send a block_actions payload.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param PlainText|string|null $placeholder Sets the placeholder text shown before a value is chosen.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string|null $actionId = null,
        string|null $initialValue = null,
        bool|null $multiline = null,
        int|null $minLength = null,
        int|null $maxLength = null,
        DispatchActionConfiguration|null $dispatchActionConfig = null,
        bool|null $focusOnLoad = null,
        PlainText|string|null $placeholder = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->initialValue = $initialValue;
        $this->multiline = $multiline;
        $this->minLength = $minLength;
        $this->maxLength = $maxLength;
        $this->dispatchActionConfig = $dispatchActionConfig;
        $this->focusOnLoad = $focusOnLoad;
        $this->placeholder = is_string($placeholder) ? new PlainText($placeholder) : $placeholder;
        parent::__construct($extensions);
    }
}
