<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A numeric data table cell with display text.
 * @see https://docs.slack.dev/reference/block-kit/blocks/data-table-block
 */
final readonly class RawNumber extends Value implements DataTableCell
{
    /** Sets the numeric value used for sorting.
     * @var int|float
     */
    public int|float $value;

    /** Sets the formatted text displayed for the number, such as 1,234.5.
     * @var string
     */
    public string $text;

    /**
     * @param int|float $value Sets the numeric value used for sorting.
     * @param string $text Sets the formatted text displayed for the number, such as 1,234.5.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        int|float $value,
        string $text,
        ?JsonObject $extensions = null,
    ) {
        $this->value = $value;
        $this->text = $text;
        parent::__construct($extensions);
    }
}
