<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** Visibility of a slash-command or interaction response. */
enum ResponseType: string
{
    /** Visible to everyone in the channel. */
    case InChannel = 'in_channel';
    /** Visible only to the user who triggered the response. */
    case Ephemeral = 'ephemeral';
}
