<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A quotation inside rich text.
 * @see https://docs.slack.dev/reference/block-kit/blocks/rich-text-block
 */
final readonly class RichTextQuote extends Value implements RichTextBlockElement
{
    /** Adds inline rich text elements in display order.
     * @var list<RichTextSectionElement>
     */
    public array $elements;

    /** Sets the width of the left border, in pixels.
     * @var int|null
     */
    public int|null $border;

    /**
     * @param list<RichTextSectionElement> $elements Adds inline rich text elements in display order.
     * @param int|null $border Sets the width of the left border, in pixels.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $elements,
        int|null $border = null,
        ?JsonObject $extensions = null,
    ) {
        $this->elements = $elements;
        $this->border = $border;
        parent::__construct($extensions);
    }
}
