<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * An input that accepts formatted rich text.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/rich-text-input-element
 */
final readonly class RichTextInputElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string
     */
    public string $actionId;

    /** Sets the rich text present when the input loads.
     * @var RichTextBlock|null
     */
    public RichTextBlock|null $initialValue;

    /** Sets which user interactions send a block_actions payload.
     * @var DispatchActionConfiguration|null
     */
    public DispatchActionConfiguration|null $dispatchActionConfig;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /** Sets the placeholder text shown before a value is chosen.
     * @var PlainText|null
     */
    public PlainText|null $placeholder;

    /** Sets the minimum visible height of the input, in lines.
     * @var int|null
     */
    public int|null $minLines;

    /** Sets the maximum visible height of the input, in lines.
     * @var int|null
     */
    public int|null $maxLines;

    /**
     * @param string $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param RichTextBlock|null $initialValue Sets the rich text present when the input loads.
     * @param DispatchActionConfiguration|null $dispatchActionConfig Sets which user interactions send a block_actions payload.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param PlainText|string|null $placeholder Sets the placeholder text shown before a value is chosen.
     * @param int|null $minLines Sets the minimum visible height of the input, in lines.
     * @param int|null $maxLines Sets the maximum visible height of the input, in lines.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $actionId,
        RichTextBlock|null $initialValue = null,
        DispatchActionConfiguration|null $dispatchActionConfig = null,
        bool|null $focusOnLoad = null,
        PlainText|string|null $placeholder = null,
        int|null $minLines = null,
        int|null $maxLines = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->initialValue = $initialValue;
        $this->dispatchActionConfig = $dispatchActionConfig;
        $this->focusOnLoad = $focusOnLoad;
        $this->placeholder = is_string($placeholder) ? new PlainText($placeholder) : $placeholder;
        $this->minLines = $minLines;
        $this->maxLines = $maxLines;
        parent::__construct($extensions);
    }
}
