<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** Marker styles for rich text lists. */
enum RichTextListStyle: string
{
    /** An unordered, bulleted list. */
    case Bullet = 'bullet';
    /** A numbered list. */
    case Ordered = 'ordered';
}
