<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * Formatted text built from sections, lists, preformatted blocks, and quotes.
 * @see https://docs.slack.dev/reference/block-kit/blocks/rich-text-block
 */
final readonly class RichTextBlock extends Value implements Block, TableCell, DataTableCell
{
    /** Adds sections, lists, preformatted blocks, and quotes in display order.
     * @var list<RichTextBlockElement>
     */
    public array $elements;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param list<RichTextBlockElement> $elements Adds sections, lists, preformatted blocks, and quotes in display order.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $elements,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->elements = $elements;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
