<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/** An inline rich text element: text, a link, an emoji, or a channel, user, or user group mention. */
interface RichTextSectionElement extends \JsonSerializable
{
    /** @return array<string, mixed> Slack wire fields. */
    public function toArray(): array;

    /** Encodes this validated value as Slack JSON. */
    public function toJson(): string;
}
