<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A user mention inside rich text.
 * @see https://docs.slack.dev/reference/block-kit/blocks/rich-text-block
 */
final readonly class RichTextUser extends Value implements RichTextSectionElement
{
    /** Sets the ID of the mentioned user.
     * @var string
     */
    public string $userId;

    /** Sets the visual style.
     * @var RichTextStyle|null
     */
    public RichTextStyle|null $style;

    /**
     * @param string $userId Sets the ID of the mentioned user.
     * @param RichTextStyle|null $style Sets the visual style.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $userId,
        RichTextStyle|null $style = null,
        ?JsonObject $extensions = null,
    ) {
        $this->userId = $userId;
        $this->style = $style;
        parent::__construct($extensions);
    }
}
