<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A paragraph of inline rich text elements.
 * @see https://docs.slack.dev/reference/block-kit/blocks/rich-text-block
 */
final readonly class RichTextSection extends Value implements RichTextBlockElement
{
    /** Adds inline rich text elements in display order.
     * @var list<RichTextSectionElement>
     */
    public array $elements;

    /**
     * @param list<RichTextSectionElement> $elements Adds inline rich text elements in display order.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array $elements,
        ?JsonObject $extensions = null,
    ) {
        $this->elements = $elements;
        parent::__construct($extensions);
    }
}
