<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A Slack-provided icon, referenced by name.
 * @see https://docs.slack.dev/reference/block-kit/blocks/card-block
 */
final readonly class SlackIcon extends Value
{
    /** Sets the name of the Slack-provided icon, such as rocket.
     * @var string
     */
    public string $name;

    /**
     * @param string $name Sets the name of the Slack-provided icon, such as rocket.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $name,
        ?JsonObject $extensions = null,
    ) {
        $this->name = $name;
        parent::__construct($extensions);
    }
}
