<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A menu for selecting one option defined in the payload.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/select-menu-element
 * Use options or option groups, not both.
 */
final readonly class StaticSelectElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Adds selectable options in display order.
     * @var list<Option>|null
     */
    public array|null $options;

    /** Adds labelled groups of options in display order. Cannot be combined with ungrouped options.
     * @var list<OptionGroup>|null
     */
    public array|null $optionGroups;

    /** Sets the option selected when the element loads. It must match an option in the element.
     * @var Option|null
     */
    public Option|null $initialOption;

    /** Sets a confirmation dialog shown before the action is sent.
     * @var Confirmation|null
     */
    public Confirmation|null $confirm;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /** Sets the placeholder text shown before a value is chosen.
     * @var PlainText|null
     */
    public PlainText|null $placeholder;

    /**
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param list<Option>|null $options Adds selectable options in display order.
     * @param list<OptionGroup>|null $optionGroups Adds labelled groups of options in display order. Cannot be combined with ungrouped options.
     * @param Option|null $initialOption Sets the option selected when the element loads. It must match an option in the element.
     * @param Confirmation|null $confirm Sets a confirmation dialog shown before the action is sent.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param PlainText|string|null $placeholder Sets the placeholder text shown before a value is chosen.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string|null $actionId = null,
        array|null $options = null,
        array|null $optionGroups = null,
        Option|null $initialOption = null,
        Confirmation|null $confirm = null,
        bool|null $focusOnLoad = null,
        PlainText|string|null $placeholder = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->options = $options;
        $this->optionGroups = $optionGroups;
        $this->initialOption = $initialOption;
        $this->confirm = $confirm;
        $this->focusOnLoad = $focusOnLoad;
        $this->placeholder = is_string($placeholder) ? new PlainText($placeholder) : $placeholder;
        parent::__construct($extensions);
    }
}
