<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * One task with its status, details, output, and sources.
 * @see https://docs.slack.dev/reference/block-kit/blocks/task-card-block
 * A standalone task card's status cannot be pending; pending is only valid for plan tasks.
 */
final readonly class TaskCardBlock extends Value implements Block
{
    /** Sets the identifier of the task.
     * @var string
     */
    public string $taskId;

    /** Sets the task title.
     * @var string
     */
    public string $title;

    /** Sets a rich text description of the task.
     * @var RichTextBlock|null
     */
    public RichTextBlock|null $details;

    /** Sets rich text describing the task's output.
     * @var RichTextBlock|null
     */
    public RichTextBlock|null $output;

    /** Adds links to the sources the task used, in display order.
     * @var list<UrlSource>|null
     */
    public array|null $sources;

    /** Sets the task's current state.
     * @var TaskStatus
     */
    public TaskStatus $status;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /**
     * @param string $taskId Sets the identifier of the task.
     * @param string $title Sets the task title.
     * @param TaskStatus $status Sets the task's current state.
     * @param RichTextBlock|null $details Sets a rich text description of the task.
     * @param RichTextBlock|null $output Sets rich text describing the task's output.
     * @param list<UrlSource>|null $sources Adds links to the sources the task used, in display order.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $taskId,
        string $title,
        TaskStatus $status,
        RichTextBlock|null $details = null,
        RichTextBlock|null $output = null,
        array|null $sources = null,
        string|null $blockId = null,
        ?JsonObject $extensions = null,
    ) {
        $this->taskId = $taskId;
        $this->title = $title;
        $this->details = $details;
        $this->output = $output;
        $this->sources = $sources;
        $this->status = $status;
        $this->blockId = $blockId;
        parent::__construct($extensions);
    }
}
