<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A linked source cited by a task card.
 * @see https://docs.slack.dev/reference/block-kit/blocks/task-card-block
 */
final readonly class UrlSource extends Value
{
    /** Sets the source URL.
     * @var string
     */
    public string $url;

    /** Sets the source link text.
     * @var string
     */
    public string $text;

    /**
     * @param string $url Sets the source URL.
     * @param string $text Sets the source link text.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $url,
        string $text,
        ?JsonObject $extensions = null,
    ) {
        $this->url = $url;
        $this->text = $text;
        parent::__construct($extensions);
    }
}
