<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A menu for selecting one workspace user.
 * @see https://docs.slack.dev/reference/block-kit/block-elements/select-menu-element
 */
final readonly class UserSelectElement extends Value implements Element, InputElement
{
    /** Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @var string|null
     */
    public string|null $actionId;

    /** Sets the user ID selected when the menu loads.
     * @var string|null
     */
    public string|null $initialUser;

    /** Sets a confirmation dialog shown before the action is sent.
     * @var Confirmation|null
     */
    public Confirmation|null $confirm;

    /** Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @var bool|null
     */
    public bool|null $focusOnLoad;

    /** Sets the placeholder text shown before a value is chosen.
     * @var PlainText|null
     */
    public PlainText|null $placeholder;

    /**
     * @param string|null $actionId Sets the identifier Slack returns in interaction payloads when a user acts on this element. It must be unique among the elements of its block.
     * @param string|null $initialUser Sets the user ID selected when the menu loads.
     * @param Confirmation|null $confirm Sets a confirmation dialog shown before the action is sent.
     * @param bool|null $focusOnLoad Sets whether the element receives focus when the view opens. Only one element per view may do so.
     * @param PlainText|string|null $placeholder Sets the placeholder text shown before a value is chosen.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string|null $actionId = null,
        string|null $initialUser = null,
        Confirmation|null $confirm = null,
        bool|null $focusOnLoad = null,
        PlainText|string|null $placeholder = null,
        ?JsonObject $extensions = null,
    ) {
        $this->actionId = $actionId;
        $this->initialUser = $initialUser;
        $this->confirm = $confirm;
        $this->focusOnLoad = $focusOnLoad;
        $this->placeholder = is_string($placeholder) ? new PlainText($placeholder) : $placeholder;
        parent::__construct($extensions);
    }
}
