<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * An embedded video player.
 * @see https://docs.slack.dev/reference/block-kit/blocks/video-block
 */
final readonly class VideoBlock extends Value implements Block
{
    /** Sets a plain-text summary of the image or video for assistive technology.
     * @var string
     */
    public string $altText;

    /** Sets the URL of the image shown before the video plays.
     * @var string
     */
    public string $thumbnailUrl;

    /** Sets the video title.
     * @var PlainText
     */
    public PlainText $title;

    /** Sets the embeddable URL of the video. The domain must be listed in the app's unfurl domains.
     * @var string
     */
    public string $videoUrl;

    /** Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @var string|null
     */
    public string|null $blockId;

    /** Sets the name of the video's author.
     * @var string|null
     */
    public string|null $authorName;

    /** Sets the video description.
     * @var PlainText|null
     */
    public PlainText|null $description;

    /** Sets the URL of the video provider's icon.
     * @var string|null
     */
    public string|null $providerIconUrl;

    /** Sets the name of the video provider, such as YouTube.
     * @var string|null
     */
    public string|null $providerName;

    /** Sets the HTTPS URL opened when the title is clicked.
     * @var string|null
     */
    public string|null $titleUrl;

    /**
     * @param string $altText Sets a plain-text summary of the image or video for assistive technology.
     * @param string $thumbnailUrl Sets the URL of the image shown before the video plays.
     * @param PlainText|string $title Sets the video title.
     * @param string $videoUrl Sets the embeddable URL of the video. The domain must be listed in the app's unfurl domains.
     * @param string|null $blockId Sets a unique identifier for this block. Slack returns it in interaction payloads, so use a stable value when you need to find the block again.
     * @param string|null $authorName Sets the name of the video's author.
     * @param PlainText|string|null $description Sets the video description.
     * @param string|null $providerIconUrl Sets the URL of the video provider's icon.
     * @param string|null $providerName Sets the name of the video provider, such as YouTube.
     * @param string|null $titleUrl Sets the HTTPS URL opened when the title is clicked.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        string $altText,
        string $thumbnailUrl,
        PlainText|string $title,
        string $videoUrl,
        string|null $blockId = null,
        string|null $authorName = null,
        PlainText|string|null $description = null,
        string|null $providerIconUrl = null,
        string|null $providerName = null,
        string|null $titleUrl = null,
        ?JsonObject $extensions = null,
    ) {
        $this->altText = $altText;
        $this->thumbnailUrl = $thumbnailUrl;
        $this->title = is_string($title) ? new PlainText($title) : $title;
        $this->videoUrl = $videoUrl;
        $this->blockId = $blockId;
        $this->authorName = $authorName;
        $this->description = is_string($description) ? new PlainText($description) : $description;
        $this->providerIconUrl = $providerIconUrl;
        $this->providerName = $providerName;
        $this->titleUrl = $titleUrl;
        parent::__construct($extensions);
    }
}
