<?php

declare(strict_types=1);

// Generated by php/generator/generate.py. Do not edit.

namespace Slackblocks;

/**
 * A payload for incoming webhooks.
 * @see https://docs.slack.dev/messaging/sending-messages-using-incoming-webhooks
 * Only blocks supported in messages are accepted.
 * Markdown block text is limited to 12,000 characters, and data table cell text to 20,000 characters, across the whole message.
 */
final readonly class WebhookMessage extends Value
{
    /** Adds the message blocks in display order.
     * @var list<Block>|null
     */
    public array|null $blocks;

    /** Adds legacy attachments in display order.
     * @var list<Attachment>|null
     */
    public array|null $attachments;

    /** Sets the fallback text used in notifications and by clients that cannot display blocks.
     * @var string|null
     */
    public string|null $text;

    /** Sets who can see the response.
     * @var ResponseType|null
     */
    public ResponseType|null $responseType;

    /** Sets whether the response replaces the message that triggered it.
     * @var bool|null
     */
    public bool|null $replaceOriginal;

    /** Sets whether the response deletes the message that triggered it.
     * @var bool|null
     */
    public bool|null $deleteOriginal;

    /** Sets whether Slack unfurls text-based links.
     * @var bool|null
     */
    public bool|null $unfurlLinks;

    /** Sets whether Slack unfurls media links.
     * @var bool|null
     */
    public bool|null $unfurlMedia;

    /** Sets message metadata as a JSON-compatible map, such as event_type and event_payload.
     * @var JsonObject|null
     */
    public JsonObject|null $metadata;

    /**
     * @param list<Block>|null $blocks Adds the message blocks in display order.
     * @param list<Attachment>|null $attachments Adds legacy attachments in display order.
     * @param string|null $text Sets the fallback text used in notifications and by clients that cannot display blocks.
     * @param ResponseType|null $responseType Sets who can see the response.
     * @param bool|null $replaceOriginal Sets whether the response replaces the message that triggered it.
     * @param bool|null $deleteOriginal Sets whether the response deletes the message that triggered it.
     * @param bool|null $unfurlLinks Sets whether Slack unfurls text-based links.
     * @param bool|null $unfurlMedia Sets whether Slack unfurls media links.
     * @param JsonObject|null $metadata Sets message metadata as a JSON-compatible map, such as event_type and event_payload.
     * @param JsonObject|null $extensions Additional JSON fields; modeled names and type are reserved.
     */
    public function __construct(
        array|null $blocks = null,
        array|null $attachments = null,
        string|null $text = null,
        ResponseType|null $responseType = null,
        bool|null $replaceOriginal = null,
        bool|null $deleteOriginal = null,
        bool|null $unfurlLinks = null,
        bool|null $unfurlMedia = null,
        JsonObject|null $metadata = null,
        ?JsonObject $extensions = null,
    ) {
        $this->blocks = $blocks;
        $this->attachments = $attachments;
        $this->text = $text;
        $this->responseType = $responseType;
        $this->replaceOriginal = $replaceOriginal;
        $this->deleteOriginal = $deleteOriginal;
        $this->unfurlLinks = $unfurlLinks;
        $this->unfurlMedia = $unfurlMedia;
        $this->metadata = $metadata;
        parent::__construct($extensions);
    }
}
