// Generated by java/generator/generate_models.py from java/generator/model.json.
package io.github.nicklambourne.slackblocks.payload;

import com.google.gson.annotations.JsonAdapter;
import io.github.nicklambourne.slackblocks.Buildable;
import io.github.nicklambourne.slackblocks.SlackObject;
import io.github.nicklambourne.slackblocks.ValidationException;
import io.github.nicklambourne.slackblocks.block.Block;
import io.github.nicklambourne.slackblocks.internal.BuilderState;
import io.github.nicklambourne.slackblocks.internal.SlackObjectJsonAdapter;
import io.github.nicklambourne.slackblocks.internal.WireObjects;
import java.util.Map;

/**
 * A legacy message attachment containing blocks and an optional color bar.
 *
 * <p>Start with {@link #builder()}, set fields with the named fluent methods, and call {@link
 * Builder#build()} to validate and create an immutable value.
 *
 * <ul>
 *   <li>Only blocks supported in messages are accepted.
 * </ul>
 *
 * @see <a
 *     href="https://docs.slack.dev/messaging/formatting-message-text#when-to-use-attachments">Slack
 *     reference</a>
 */
@JsonAdapter(SlackObjectJsonAdapter.class)
public final class Attachment implements SlackObject {
  private final Map<String, Object> values;
  private final int hash;

  private Attachment(Map<String, Object> values) {
    this.values = values;
    this.hash = values.hashCode();
  }

  /**
   * Starts a new builder.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Map<String, Object> toMap() {
    return values;
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof Attachment that && values.equals(that.values));
  }

  @Override
  public int hashCode() {
    return hash;
  }

  /**
   * Returns this value's compact Slack JSON.
   *
   * @return compact JSON
   */
  @Override
  public String toString() {
    return toJson();
  }

  /** Fluent builder for {@link Attachment}. Builders are mutable and not thread-safe. */
  public static final class Builder implements Buildable<Attachment> {
    private final BuilderState state = new BuilderState("Attachment", "");

    private Builder() {}

    /**
     * Adds the attachment's blocks in display order.
     *
     * <p>Each call appends to any values already added.
     *
     * @param values {@link Block} values appended in order
     * @return this builder
     */
    public Builder blocks(Block... values) {
      state.append("blocks", (Object[]) values);
      return this;
    }

    /**
     * Sets the attachment's left border color: a six-digit hex color or good, warning, or danger.
     *
     * @param value value for Slack's {@code color} field
     * @return this builder
     */
    public Builder color(String value) {
      state.set("color", value);
      return this;
    }

    /**
     * Sets plain-text summary shown in clients that cannot display attachments.
     *
     * @param value value for Slack's {@code fallback} field
     * @return this builder
     */
    public Builder fallback(String value) {
      state.set("fallback", value);
      return this;
    }

    /**
     * Sets a Slack field that has no named method yet, such as a field Slack introduced after this
     * release. Prefer the named methods, which are typed and documented.
     *
     * <p>The value is checked at build time like any other field. It must be a string, number,
     * boolean, slackblocks value or builder, or a list or map containing only those.
     *
     * @param field Slack JSON field name
     * @param value JSON-compatible value
     * @return this builder
     * @throws IllegalArgumentException if the field name is empty or the value cannot be written as
     *     Slack JSON
     */
    public Builder wireField(String field, Object value) {
      if (field.isEmpty()) {
        throw new IllegalArgumentException("field must not be empty");
      }
      state.set(field, WireObjects.requireWireValue(field, value));
      return this;
    }

    /**
     * Validates the configured fields and creates an immutable value. The builder can be reused.
     *
     * @return an immutable {@link Attachment}
     * @throws ValidationException if the value breaks a Block Kit rule, such as a missing required
     *     field or an exceeded length limit
     */
    @Override
    public Attachment build() {
      if (state.get("color") instanceof String color
          && color.length() == 6
          && !color.equals("danger")
          && !color.equals("good")
          && !color.equals("warning")) {
        state.set("color", "#" + color);
      }
      return state.build(Attachment::new);
    }
  }
}
