name: Publish Docs On Release
on:
    release:
      types: [published]
permissions:
    contents: write
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check Out Source Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set Up Python Environment
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Poetry
          uses: snok/install-poetry@v1

        - name: Configure Git
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

        - name: Install Docs Dependencies
          run: |
            poetry install --no-interaction --no-root --only docs

        - name: Build and Deploy Docs
          run: |
            mike deploy --push --update-aliases ${{ github.ref_name }} latest
