name: Publish SlackBlocks Python Package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync

      - name: Build Package
        run: uv build

      - name: Publish Package
        uses: celsiusnarhwal/uv-publish@v1
        with:
          python-version: "3.11"
          token: ${{ secrets.PYPI_TOKEN }}