name: Publish SlackBlocks Python Package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.11
          poetry-version: 1.3.1
          token: ${{ secrets.PYPI_TOKEN }}
          build: true
