name: Type Checking
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-checking:
    runs-on: ubuntu-latest
    name: mypy Type Checking
    steps:
      - name: Check Out Source Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --only dev

      - name: Type Checking
        run: uv run mypy slackblocks